from __future__ import annotations

from typing import Optional

from sqlalchemy import BigInteger, Column, Float, ForeignKey, String
from sqlmodel import Field, SQLModel

# Generated by Consist schema export (schema_id=703af07c581e0e73bb32bff080f22cae90341ebabd7de03b2070ffa5fcdafcfd).
# NOTE: These are schema stubs for ActivitySim inputs; they are abstract so they
# can be imported without defining primary keys. To map them as real tables,
# remove `__abstract__` and add primary keys + relationships.
# NOTE: When using SQLModel with sa_column=Column(...), index=True must live on
# the Column itself (Field(index=...) is rejected in that case).

class HouseholdsAsimIn(SQLModel, table=True):
    __tablename__ = 'HouseholdsAsimIn'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    household_id: Optional[int] = Field(
        default=None,
        description='Household identifier used to relate persons to households.',
        sa_column=Column('household_id', BigInteger, nullable=True, index=True),
    )
    gt2: Optional[float] = Field(default=None, sa_column=Column('gt2', Float, nullable=True))
    workers: Optional[float] = Field(default=None, sa_column=Column('workers', Float, nullable=True))
    hispanic_head: Optional[str] = Field(default=None, sa_column=Column('hispanic_head', String, nullable=True))
    block_id: Optional[int] = Field(
        default=None,
        description='Census block identifier for household location.',
        sa_column=Column('block_id', BigInteger, nullable=True, index=True),
    )
    recent_mover: Optional[str] = Field(default=None, sa_column=Column('recent_mover', String, nullable=True))
    seniors: Optional[float] = Field(default=None, sa_column=Column('seniors', Float, nullable=True))
    cars: Optional[int] = Field(default=None, sa_column=Column('cars', BigInteger, nullable=True))
    hh_race_of_head: Optional[str] = Field(default=None, sa_column=Column('hh_race_of_head', String, nullable=True))
    age_of_head: Optional[float] = Field(default=None, sa_column=Column('age_of_head', Float, nullable=True))
    serialno: Optional[int] = Field(default=None, sa_column=Column('serialno', BigInteger, nullable=True))
    lcm_county_id: Optional[int] = Field(default=None, sa_column=Column('lcm_county_id', BigInteger, nullable=True))
    hh_children: Optional[str] = Field(default=None, sa_column=Column('hh_children', String, nullable=True))
    tenure: Optional[str] = Field(default=None, sa_column=Column('tenure', String, nullable=True))
    hh_age_of_head: Optional[str] = Field(default=None, sa_column=Column('hh_age_of_head', String, nullable=True))
    sf_detached: Optional[str] = Field(default=None, sa_column=Column('sf_detached', String, nullable=True))
    income: Optional[float] = Field(default=None, sa_column=Column('income', Float, nullable=True))
    tenure_mover: Optional[str] = Field(default=None, sa_column=Column('tenure_mover', String, nullable=True))
    race_of_head: Optional[float] = Field(default=None, sa_column=Column('race_of_head', Float, nullable=True))
    hh_seniors: Optional[str] = Field(default=None, sa_column=Column('hh_seniors', String, nullable=True))
    hh_size: Optional[str] = Field(default=None, sa_column=Column('hh_size', String, nullable=True))
    hh_cars: Optional[str] = Field(default=None, sa_column=Column('hh_cars', String, nullable=True))
    hispanic_status_of_head: Optional[float] = Field(default=None, sa_column=Column('hispanic_status_of_head', Float, nullable=True))
    gt55: Optional[float] = Field(default=None, sa_column=Column('gt55', Float, nullable=True))
    hh_workers: Optional[str] = Field(default=None, sa_column=Column('hh_workers', String, nullable=True))
    hh_income: Optional[str] = Field(default=None, sa_column=Column('hh_income', String, nullable=True))
    hh_type: Optional[int] = Field(default=None, sa_column=Column('hh_type', BigInteger, nullable=True))
    persons: Optional[int] = Field(default=None, sa_column=Column('persons', BigInteger, nullable=True))
    taz: Optional[int] = Field(
        default=None,
        description='Traffic analysis zone for household location.',
        sa_column=Column(
            'TAZ',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    hht: Optional[int] = Field(default=None, sa_column=Column('HHT', BigInteger, nullable=True))


# Generated by Consist schema export (schema_id=494c3527d97e3413a861439aafb52cea2c640c634796a28143e1a8db25431432).

class LandUseAsimIn(SQLModel, table=True):
    __tablename__ = 'LandUseAsimIn'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    taz: Optional[int] = Field(
        default=None,
        description='Traffic analysis zone identifier for land use.',
        sa_column=Column('TAZ', BigInteger, nullable=True, index=True),
    )
    objectid: Optional[int] = Field(default=None, sa_column=Column('objectid', BigInteger, nullable=True))
    district: Optional[int] = Field(default=None, sa_column=Column('district', BigInteger, nullable=True))
    county: Optional[str] = Field(default=None, sa_column=Column('county', String, nullable=True))
    gacres: Optional[float] = Field(default=None, sa_column=Column('gacres', Float, nullable=True))
    geometry: Optional[str] = Field(
        default=None,
        description='Serialized geometry if provided by upstream land-use processing.',
        sa_column=Column('geometry', String, nullable=True),
    )
    age0004: Optional[float] = Field(default=None, sa_column=Column('AGE0004', Float, nullable=True))
    age0519: Optional[float] = Field(default=None, sa_column=Column('AGE0519', Float, nullable=True))
    age2044: Optional[float] = Field(default=None, sa_column=Column('AGE2044', Float, nullable=True))
    age4564: Optional[float] = Field(default=None, sa_column=Column('AGE4564', Float, nullable=True))
    age64p: Optional[float] = Field(default=None, sa_column=Column('AGE64P', Float, nullable=True))
    age62p: Optional[float] = Field(default=None, sa_column=Column('AGE62P', Float, nullable=True))
    totpop: Optional[float] = Field(default=None, sa_column=Column('TOTPOP', Float, nullable=True))
    hhincq1: Optional[float] = Field(default=None, sa_column=Column('HHINCQ1', Float, nullable=True))
    hhincq2: Optional[float] = Field(default=None, sa_column=Column('HHINCQ2', Float, nullable=True))
    hhincq3: Optional[float] = Field(default=None, sa_column=Column('HHINCQ3', Float, nullable=True))
    hhincq4: Optional[float] = Field(default=None, sa_column=Column('HHINCQ4', Float, nullable=True))
    empres: Optional[float] = Field(default=None, sa_column=Column('EMPRES', Float, nullable=True))
    tothh: Optional[float] = Field(default=None, sa_column=Column('TOTHH', Float, nullable=True))
    retempn: Optional[int] = Field(default=None, sa_column=Column('RETEMPN', BigInteger, nullable=True))
    fpsempn: Optional[int] = Field(default=None, sa_column=Column('FPSEMPN', BigInteger, nullable=True))
    herempn: Optional[int] = Field(default=None, sa_column=Column('HEREMPN', BigInteger, nullable=True))
    agrempn: Optional[int] = Field(default=None, sa_column=Column('AGREMPN', BigInteger, nullable=True))
    mwtempn: Optional[int] = Field(default=None, sa_column=Column('MWTEMPN', BigInteger, nullable=True))
    totemp: Optional[int] = Field(default=None, sa_column=Column('TOTEMP', BigInteger, nullable=True))
    othempn: Optional[int] = Field(default=None, sa_column=Column('OTHEMPN', BigInteger, nullable=True))
    shpop62p: Optional[float] = Field(default=None, sa_column=Column('SHPOP62P', Float, nullable=True))
    totacre: Optional[float] = Field(default=None, sa_column=Column('TOTACRE', Float, nullable=True))
    hsenroll: Optional[float] = Field(default=None, sa_column=Column('HSENROLL', Float, nullable=True))
    topology: Optional[int] = Field(default=None, sa_column=Column('TOPOLOGY', BigInteger, nullable=True))
    employment_density: Optional[float] = Field(default=None, sa_column=Column('employment_density', Float, nullable=True))
    pop_density: Optional[float] = Field(default=None, sa_column=Column('pop_density', Float, nullable=True))
    hh_density: Optional[float] = Field(default=None, sa_column=Column('hh_density', Float, nullable=True))
    hq1_density: Optional[float] = Field(default=None, sa_column=Column('hq1_density', Float, nullable=True))
    prkcst: Optional[float] = Field(default=None, sa_column=Column('PRKCST', Float, nullable=True))
    oprkcst: Optional[float] = Field(default=None, sa_column=Column('OPRKCST', Float, nullable=True))
    collfte: Optional[float] = Field(default=None, sa_column=Column('COLLFTE', Float, nullable=True))
    collpte: Optional[float] = Field(default=None, sa_column=Column('COLLPTE', Float, nullable=True))
    terminal: Optional[int] = Field(default=None, sa_column=Column('TERMINAL', BigInteger, nullable=True))
    area_type_metric: Optional[float] = Field(default=None, sa_column=Column('area_type_metric', Float, nullable=True))
    area_type: Optional[int] = Field(default=None, sa_column=Column('area_type', BigInteger, nullable=True))
    county__2: Optional[int] = Field(default=None, sa_column=Column('COUNTY', BigInteger, nullable=True))

class PersonsAsimIn(SQLModel, table=True):
    __tablename__ = 'PersonsAsimIn'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    person_id: Optional[int] = Field(
        default=None,
        description='Person identifier unique within the input population.',
        sa_column=Column('person_id', BigInteger, nullable=True, index=True),
    )
    relate: Optional[int] = Field(default=None, sa_column=Column('relate', BigInteger, nullable=True))
    hispanic: Optional[float] = Field(default=None, sa_column=Column('hispanic', Float, nullable=True))
    student: Optional[float] = Field(default=None, sa_column=Column('student', Float, nullable=True))
    person_sex: Optional[str] = Field(default=None, sa_column=Column('person_sex', String, nullable=True))
    p_hispanic: Optional[str] = Field(default=None, sa_column=Column('p_hispanic', String, nullable=True))
    mar: Optional[int] = Field(default=None, sa_column=Column('MAR', BigInteger, nullable=True))
    person_age: Optional[str] = Field(default=None, sa_column=Column('person_age', String, nullable=True))
    edu: Optional[float] = Field(default=None, sa_column=Column('edu', Float, nullable=True))
    age: Optional[float] = Field(default=None, sa_column=Column('age', Float, nullable=True))
    work_at_home: Optional[float] = Field(default=None, sa_column=Column('work_at_home', Float, nullable=True))
    race: Optional[str] = Field(default=None, sa_column=Column('race', String, nullable=True))
    age_group: Optional[str] = Field(default=None, sa_column=Column('age_group', String, nullable=True))
    hours: Optional[float] = Field(default=None, sa_column=Column('hours', Float, nullable=True))
    earning: Optional[float] = Field(default=None, sa_column=Column('earning', Float, nullable=True))
    household_id: Optional[int] = Field(
        default=None,
        description='Household identifier to link persons to households.',
        sa_column=Column(
            'household_id',
            BigInteger,
            ForeignKey('HouseholdsAsimIn.household_id'),
            nullable=True,
            index=True,
        ),
    )
    sex: Optional[float] = Field(default=None, sa_column=Column('sex', Float, nullable=True))
    member_id: Optional[int] = Field(default=None, sa_column=Column('member_id', BigInteger, nullable=True))
    school_taz: Optional[int] = Field(
        default=None,
        description='School location in TAZ geography.',
        sa_column=Column(
            'school_taz',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    school_zone_id: Optional[int] = Field(
        default=None,
        sa_column=Column(
            'school_zone_id',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    school_id: Optional[int] = Field(default=None, sa_column=Column('school_id', BigInteger, nullable=True))
    hispanic_1: Optional[float] = Field(default=None, sa_column=Column('hispanic.1', Float, nullable=True))
    race_id: Optional[float] = Field(default=None, sa_column=Column('race_id', Float, nullable=True))
    worker: Optional[float] = Field(default=None, sa_column=Column('worker', Float, nullable=True))
    work_block_id: Optional[int] = Field(
        default=None,
        description='Work location in census block geography.',
        sa_column=Column('work_block_id', BigInteger, nullable=True, index=True),
    )
    education_group: Optional[str] = Field(default=None, sa_column=Column('education_group', String, nullable=True))
    work_zone_id: Optional[int] = Field(
        default=None,
        sa_column=Column(
            'work_zone_id',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    workplace_taz: Optional[int] = Field(
        default=None,
        description='Workplace location in TAZ geography.',
        sa_column=Column(
            'workplace_taz',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    school_block_id: Optional[int] = Field(
        default=None,
        description='School location in census block geography.',
        sa_column=Column('school_block_id', BigInteger, nullable=True, index=True),
    )
    taz: Optional[int] = Field(
        default=None,
        description='Home location in TAZ geography.',
        sa_column=Column(
            'TAZ',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    ptype: Optional[int] = Field(default=None, sa_column=Column('ptype', BigInteger, nullable=True))
    pemploy: Optional[int] = Field(default=None, sa_column=Column('pemploy', BigInteger, nullable=True))
    pstudent: Optional[int] = Field(default=None, sa_column=Column('pstudent', BigInteger, nullable=True))
    home_x: Optional[float] = Field(default=None, sa_column=Column('home_x', Float, nullable=True))
    home_y: Optional[float] = Field(default=None, sa_column=Column('home_y', Float, nullable=True))

class BeamPlansAsimOut(SQLModel, table=True):
    __tablename__ = 'BeamPlansAsimOut'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    tour_id: Optional[int] = Field(default=None, sa_column=Column('tour_id', BigInteger, nullable=True))
    trip_id: Optional[int] = Field(default=None, sa_column=Column('trip_id', BigInteger, nullable=True))
    person_id: Optional[int] = Field(default=None, sa_column=Column('person_id', BigInteger, nullable=True))
    number_of_participants: Optional[float] = Field(default=None, sa_column=Column('number_of_participants', Float, nullable=True))
    tour_mode: Optional[str] = Field(default=None, sa_column=Column('tour_mode', String, nullable=True))
    trip_mode: Optional[str] = Field(default=None, sa_column=Column('trip_mode', String, nullable=True))
    planelementindex: Optional[int] = Field(default=None, sa_column=Column('PlanElementIndex', BigInteger, nullable=True))
    activityelement: Optional[str] = Field(default=None, sa_column=Column('ActivityElement', String, nullable=True))
    activitytype: Optional[str] = Field(default=None, sa_column=Column('ActivityType', String, nullable=True))
    x: Optional[float] = Field(default=None, sa_column=Column('x', Float, nullable=True))
    y: Optional[float] = Field(default=None, sa_column=Column('y', Float, nullable=True))
    departure_time: Optional[float] = Field(default=None, sa_column=Column('departure_time', Float, nullable=True))
    trip_dur_min: Optional[float] = Field(default=None, sa_column=Column('trip_dur_min', Float, nullable=True))
    trip_cost_dollars: Optional[float] = Field(default=None, sa_column=Column('trip_cost_dollars', Float, nullable=True))