from __future__ import annotations

from typing import Optional

from sqlalchemy import BigInteger, Boolean, Column, Float, ForeignKey, String
from sqlmodel import Field, SQLModel

# Generated by Consist schema export (schema_id=1d44d4bb11e7c26277e9fe4a4f386527d7f423718c3060132c33e2499ffb314f).
# NOTE: These are schema stubs for Atlas inputs/outputs; they are abstract so
# they can be imported without defining primary keys. To map them as real
# tables, remove `__abstract__` and add primary keys + relationships.
# NOTE: When using SQLModel with sa_column=Column(...), index=True must live on
# the Column itself (Field(index=...) is rejected in that case).


class AtlasBlocks(SQLModel, table=True):
    __tablename__ = 'AtlasBlocks'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    block_id: Optional[str] = Field(
        default=None,
        description='Census block identifier.',
        sa_column=Column('block_id', String, primary_key=True, nullable=True, index=True),
    )
    cousub: Optional[int] = Field(
        default=None,
        description='County subdivision identifier for the block.',
        sa_column=Column('cousub', BigInteger, nullable=True),
    )
    square_meters_land: Optional[int] = Field(
        default=None,
        description='Land area for the block in square meters.',
        sa_column=Column('square_meters_land', BigInteger, nullable=True),
    )
    tract_id: Optional[str] = Field(
        default=None,
        description='Census tract identifier for the block.',
        sa_column=Column('tract_id', String, nullable=True),
    )
    residential_unit_capacity: Optional[float] = Field(
        default=None,
        description='Estimated residential unit capacity for the block.',
        sa_column=Column('residential_unit_capacity', Float, nullable=True),
    )
    y: Optional[float] = Field(
        default=None,
        description='Y coordinate of the block centroid.',
        sa_column=Column('y', Float, nullable=True),
    )
    employment_capacity: Optional[float] = Field(
        default=None,
        description='Estimated employment capacity for the block.',
        sa_column=Column('employment_capacity', Float, nullable=True),
    )
    county_id: Optional[str] = Field(
        default=None,
        description='County identifier for the block.',
        sa_column=Column('county_id', String, nullable=True),
    )
    zone_id: Optional[int] = Field(
        default=None,
        description='Model zone identifier for the block (often a TAZ).',
        sa_column=Column(
            'zone_id',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    taz_zone_id: Optional[int] = Field(
        default=None,
        description='Traffic analysis zone identifier for the block.',
        sa_column=Column(
            'taz_zone_id',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    x: Optional[float] = Field(
        default=None,
        description='X coordinate of the block centroid.',
        sa_column=Column('x', Float, nullable=True),
    )
    block_group_id: Optional[str] = Field(
        default=None,
        description='Census block group identifier for the block.',
        sa_column=Column('block_group_id', String, nullable=True),
    )
    mpo_id: Optional[str] = Field(
        default=None,
        description='Metropolitan planning organization identifier.',
        sa_column=Column('MPO_ID', String, nullable=True),
    )
    sum_acres: Optional[float] = Field(
        default=None,
        description='Land area for the block in acres.',
        sa_column=Column('sum_acres', Float, nullable=True),
    )
    state_id: Optional[str] = Field(
        default=None,
        description='State identifier for the block.',
        sa_column=Column('state_id', String, nullable=True),
    )
    node_id: Optional[int] = Field(
        default=None,
        description='Network node identifier associated with the block centroid.',
        sa_column=Column('node_id', BigInteger, nullable=True, index=True),
    )


class AtlasGrave(SQLModel, table=True):
    __tablename__ = 'AtlasGrave'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    person_id: Optional[int] = Field(
        default=None,
        description='Person identifier (proposed primary key).',
        sa_column=Column('person_id', BigInteger, primary_key=True, nullable=True, index=True),
    )
    p_hispanic: Optional[bool] = Field(
        default=None,
        description='Boolean indicator for Hispanic/Latino ethnicity.',
        sa_column=Column('p_hispanic', Boolean, nullable=True),
    )
    person_age: Optional[str] = Field(
        default=None,
        description='Age category for the person.',
        sa_column=Column('person_age', String, nullable=True),
    )
    race_id: Optional[float] = Field(
        default=None,
        description='Race category identifier for the person.',
        sa_column=Column('race_id', Float, nullable=True),
    )
    school_id: Optional[int] = Field(
        default=None,
        description='School identifier associated with the person.',
        sa_column=Column('school_id', BigInteger, nullable=True),
    )
    education_group: Optional[str] = Field(
        default=None,
        description='Education category or attainment group.',
        sa_column=Column('education_group', String, nullable=True),
    )
    workplace_taz: Optional[int] = Field(
        default=None,
        description='Workplace traffic analysis zone identifier.',
        sa_column=Column(
            'workplace_taz',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    school_block_id: Optional[int] = Field(
        default=None,
        description='Census block identifier for school location.',
        sa_column=Column(
            'school_block_id',
            BigInteger,
            ForeignKey('AtlasBlocks.block_id'),
            nullable=True,
            index=True,
        ),
    )
    school_zone_id: Optional[int] = Field(
        default=None,
        description='School traffic analysis zone identifier.',
        sa_column=Column(
            'school_zone_id',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    person_sex: Optional[str] = Field(
        default=None,
        description='Sex category for the person.',
        sa_column=Column('person_sex', String, nullable=True),
    )
    relate: Optional[float] = Field(
        default=None,
        description='Relationship to household head code.',
        sa_column=Column('relate', Float, nullable=True),
    )
    work_at_home: Optional[float] = Field(
        default=None,
        description='Indicator for working at home.',
        sa_column=Column('work_at_home', Float, nullable=True),
    )
    hours: Optional[float] = Field(
        default=None,
        description='Weekly work hours for the person.',
        sa_column=Column('hours', Float, nullable=True),
    )
    earning: Optional[float] = Field(
        default=None,
        description='Annual or hourly earnings for the person.',
        sa_column=Column('earning', Float, nullable=True),
    )
    work_block_id: Optional[str] = Field(
        default=None,
        description='Census block identifier for workplace location.',
        sa_column=Column(
            'work_block_id',
            String,
            ForeignKey('AtlasBlocks.block_id'),
            nullable=True,
            index=True,
        ),
    )
    student: Optional[float] = Field(
        default=None,
        description='Indicator for student status.',
        sa_column=Column('student', Float, nullable=True),
    )
    hispanic: Optional[float] = Field(
        default=None,
        description='Hispanic status code (legacy encoding).',
        sa_column=Column('hispanic', Float, nullable=True),
    )
    worker: Optional[float] = Field(
        default=None,
        description='Worker status code.',
        sa_column=Column('worker', Float, nullable=True),
    )
    age_group: Optional[str] = Field(
        default=None,
        description='Age group category for the person.',
        sa_column=Column('age_group', String, nullable=True),
    )
    member_id: Optional[int] = Field(
        default=None,
        description='Household member identifier within the household.',
        sa_column=Column('member_id', BigInteger, nullable=True),
    )
    work_zone_id: Optional[int] = Field(
        default=None,
        description='Workplace zone identifier (often a TAZ).',
        sa_column=Column(
            'work_zone_id',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    sex: Optional[float] = Field(
        default=None,
        description='Sex code (legacy encoding).',
        sa_column=Column('sex', Float, nullable=True),
    )
    race: Optional[str] = Field(
        default=None,
        description='Race category label.',
        sa_column=Column('race', String, nullable=True),
    )
    hispanic_1: Optional[float] = Field(
        default=None,
        description='Hispanic status code (alternate encoding).',
        sa_column=Column('hispanic.1', Float, nullable=True),
    )
    age: Optional[float] = Field(
        default=None,
        description='Age in years.',
        sa_column=Column('age', Float, nullable=True),
    )
    household_id: Optional[float] = Field(
        default=None,
        description='Household identifier associated with the person.',
        sa_column=Column(
            'household_id',
            Float,
            ForeignKey('AtlasHousehold.household_id'),
            nullable=True,
            index=True,
        ),
    )
    school_taz: Optional[int] = Field(
        default=None,
        description='School traffic analysis zone identifier.',
        sa_column=Column(
            'school_taz',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    mar: Optional[float] = Field(
        default=None,
        description='Marital status code.',
        sa_column=Column('MAR', Float, nullable=True),
    )
    edu: Optional[float] = Field(
        default=None,
        description='Education attainment code.',
        sa_column=Column('edu', Float, nullable=True),
    )


class AtlasHousehold(SQLModel, table=True):
    __tablename__ = 'AtlasHousehold'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    household_id: Optional[float] = Field(
        default=None,
        description='Household identifier (proposed primary key).',
        sa_column=Column('household_id', Float, primary_key=True, nullable=True, index=True),
    )
    tenure: Optional[str] = Field(
        default=None,
        description='Housing tenure category for the household.',
        sa_column=Column('tenure', String, nullable=True),
    )
    block_id: Optional[str] = Field(
        default=None,
        description='Census block identifier for household location.',
        sa_column=Column(
            'block_id',
            String,
            ForeignKey('AtlasBlocks.block_id'),
            nullable=True,
            index=True,
        ),
    )
    hh_age_of_head: Optional[str] = Field(
        default=None,
        description='Age category of the household head.',
        sa_column=Column('hh_age_of_head', String, nullable=True),
    )
    gt55: Optional[float] = Field(
        default=None,
        description='Indicator for household head age greater than 55.',
        sa_column=Column('gt55', Float, nullable=True),
    )
    age_of_head: Optional[float] = Field(
        default=None,
        description='Age of the household head in years.',
        sa_column=Column('age_of_head', Float, nullable=True),
    )
    serialno: Optional[int] = Field(
        default=None,
        description='ACS/PUF serial number for the household.',
        sa_column=Column('serialno', BigInteger, nullable=True),
    )
    gt2: Optional[float] = Field(
        default=None,
        description='Indicator for household size greater than 2.',
        sa_column=Column('gt2', Float, nullable=True),
    )
    seniors: Optional[float] = Field(
        default=None,
        description='Number of seniors in the household.',
        sa_column=Column('seniors', Float, nullable=True),
    )
    hh_children: Optional[bool] = Field(
        default=None,
        description='Indicator for presence of children in household.',
        sa_column=Column('hh_children', Boolean, nullable=True),
    )
    recent_mover: Optional[str] = Field(
        default=None,
        description='Recent mover category for the household.',
        sa_column=Column('recent_mover', String, nullable=True),
    )
    hh_seniors: Optional[bool] = Field(
        default=None,
        description='Indicator for presence of seniors in household.',
        sa_column=Column('hh_seniors', Boolean, nullable=True),
    )
    tenure_mover: Optional[str] = Field(
        default=None,
        description='Tenure/mover category for the household.',
        sa_column=Column('tenure_mover', String, nullable=True),
    )
    workers: Optional[float] = Field(
        default=None,
        description='Number of workers in the household.',
        sa_column=Column('workers', Float, nullable=True),
    )
    race_of_head: Optional[float] = Field(
        default=None,
        description='Race code for the household head.',
        sa_column=Column('race_of_head', Float, nullable=True),
    )
    hispanic_status_of_head: Optional[float] = Field(
        default=None,
        description='Hispanic status code for the household head.',
        sa_column=Column('hispanic_status_of_head', Float, nullable=True),
    )
    cars: Optional[float] = Field(
        default=None,
        description='Number of vehicles owned by the household.',
        sa_column=Column('cars', Float, nullable=True),
    )
    hh_cars: Optional[str] = Field(
        default=None,
        description='Vehicle ownership category for the household.',
        sa_column=Column('hh_cars', String, nullable=True),
    )
    lcm_county_id: Optional[str] = Field(
        default=None,
        description='County identifier used by land change modeling.',
        sa_column=Column('lcm_county_id', String, nullable=True),
    )
    hispanic_head: Optional[bool] = Field(
        default=None,
        description='Boolean indicator for Hispanic household head.',
        sa_column=Column('hispanic_head', Boolean, nullable=True),
    )
    hh_size: Optional[str] = Field(
        default=None,
        description='Household size category.',
        sa_column=Column('hh_size', String, nullable=True),
    )
    income: Optional[float] = Field(
        default=None,
        description='Household income.',
        sa_column=Column('income', Float, nullable=True),
    )
    hh_race_of_head: Optional[str] = Field(
        default=None,
        description='Race category of household head.',
        sa_column=Column('hh_race_of_head', String, nullable=True),
    )
    hh_income: Optional[str] = Field(
        default=None,
        description='Household income category.',
        sa_column=Column('hh_income', String, nullable=True),
    )
    hh_workers: Optional[str] = Field(
        default=None,
        description='Household worker category.',
        sa_column=Column('hh_workers', String, nullable=True),
    )
    sf_detached: Optional[str] = Field(
        default=None,
        description='Single-family detached indicator/category.',
        sa_column=Column('sf_detached', String, nullable=True),
    )
    persons: Optional[int] = Field(
        default=None,
        description='Household size (number of persons).',
        sa_column=Column('persons', BigInteger, nullable=True),
    )
    hh_type: Optional[int] = Field(
        default=None,
        description='Household type code.',
        sa_column=Column('hh_type', BigInteger, nullable=True),
    )


class AtlasJobs(SQLModel, table=True):
    __tablename__ = 'AtlasJobs'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    job_id: Optional[int] = Field(
        default=None,
        description='Job identifier (proposed primary key).',
        sa_column=Column('job_id', BigInteger, primary_key=True, nullable=True, index=True),
    )
    sector_id: Optional[int] = Field(
        default=None,
        description='Detailed employment sector identifier.',
        sa_column=Column('sector_id', BigInteger, nullable=True),
    )
    agg_sector: Optional[int] = Field(
        default=None,
        description='Aggregated employment sector identifier.',
        sa_column=Column('agg_sector', BigInteger, nullable=True),
    )
    lcm_county_id: Optional[str] = Field(
        default=None,
        description='County identifier used by land change modeling.',
        sa_column=Column('lcm_county_id', String, nullable=True),
    )
    block_id: Optional[str] = Field(
        default=None,
        description='Census block identifier for job location.',
        sa_column=Column(
            'block_id',
            String,
            ForeignKey('AtlasBlocks.block_id'),
            nullable=True,
            index=True,
        ),
    )


class AtlasPersons(SQLModel, table=True):
    __tablename__ = 'AtlasPersons'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    person_id: Optional[int] = Field(
        default=None,
        description='Person identifier (proposed primary key).',
        sa_column=Column('person_id', BigInteger, primary_key=True, nullable=True, index=True),
    )
    p_hispanic: Optional[bool] = Field(
        default=None,
        description='Boolean indicator for Hispanic/Latino ethnicity.',
        sa_column=Column('p_hispanic', Boolean, nullable=True),
    )
    person_age: Optional[str] = Field(
        default=None,
        description='Age category for the person.',
        sa_column=Column('person_age', String, nullable=True),
    )
    race_id: Optional[float] = Field(
        default=None,
        description='Race category identifier for the person.',
        sa_column=Column('race_id', Float, nullable=True),
    )
    school_id: Optional[int] = Field(
        default=None,
        description='School identifier associated with the person.',
        sa_column=Column('school_id', BigInteger, nullable=True),
    )
    education_group: Optional[str] = Field(
        default=None,
        description='Education category or attainment group.',
        sa_column=Column('education_group', String, nullable=True),
    )
    workplace_taz: Optional[int] = Field(
        default=None,
        description='Workplace traffic analysis zone identifier.',
        sa_column=Column(
            'workplace_taz',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    school_block_id: Optional[int] = Field(
        default=None,
        description='Census block identifier for school location.',
        sa_column=Column(
            'school_block_id',
            BigInteger,
            ForeignKey('AtlasBlocks.block_id'),
            nullable=True,
            index=True,
        ),
    )
    school_zone_id: Optional[int] = Field(
        default=None,
        description='School traffic analysis zone identifier.',
        sa_column=Column(
            'school_zone_id',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    person_sex: Optional[str] = Field(
        default=None,
        description='Sex category for the person.',
        sa_column=Column('person_sex', String, nullable=True),
    )
    relate: Optional[int] = Field(
        default=None,
        description='Relationship to household head code.',
        sa_column=Column('relate', BigInteger, nullable=True),
    )
    work_at_home: Optional[float] = Field(
        default=None,
        description='Indicator for working at home.',
        sa_column=Column('work_at_home', Float, nullable=True),
    )
    hours: Optional[float] = Field(
        default=None,
        description='Weekly work hours for the person.',
        sa_column=Column('hours', Float, nullable=True),
    )
    earning: Optional[float] = Field(
        default=None,
        description='Annual or hourly earnings for the person.',
        sa_column=Column('earning', Float, nullable=True),
    )
    student: Optional[float] = Field(
        default=None,
        description='Indicator for student status.',
        sa_column=Column('student', Float, nullable=True),
    )
    work_block_id: Optional[str] = Field(
        default=None,
        description='Census block identifier for workplace location.',
        sa_column=Column(
            'work_block_id',
            String,
            ForeignKey('AtlasBlocks.block_id'),
            nullable=True,
            index=True,
        ),
    )
    hispanic: Optional[float] = Field(
        default=None,
        description='Hispanic status code (legacy encoding).',
        sa_column=Column('hispanic', Float, nullable=True),
    )
    worker: Optional[float] = Field(
        default=None,
        description='Worker status code.',
        sa_column=Column('worker', Float, nullable=True),
    )
    age_group: Optional[str] = Field(
        default=None,
        description='Age group category for the person.',
        sa_column=Column('age_group', String, nullable=True),
    )
    member_id: Optional[int] = Field(
        default=None,
        description='Household member identifier within the household.',
        sa_column=Column('member_id', BigInteger, nullable=True),
    )
    work_zone_id: Optional[int] = Field(
        default=None,
        description='Workplace zone identifier (often a TAZ).',
        sa_column=Column(
            'work_zone_id',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    sex: Optional[float] = Field(
        default=None,
        description='Sex code (legacy encoding).',
        sa_column=Column('sex', Float, nullable=True),
    )
    race: Optional[str] = Field(
        default=None,
        description='Race category label.',
        sa_column=Column('race', String, nullable=True),
    )
    hispanic_1: Optional[float] = Field(
        default=None,
        description='Hispanic status code (alternate encoding).',
        sa_column=Column('hispanic.1', Float, nullable=True),
    )
    age: Optional[float] = Field(
        default=None,
        description='Age in years.',
        sa_column=Column('age', Float, nullable=True),
    )
    household_id: Optional[float] = Field(
        default=None,
        description='Household identifier associated with the person.',
        sa_column=Column(
            'household_id',
            Float,
            ForeignKey('AtlasHousehold.household_id'),
            nullable=True,
            index=True,
        ),
    )
    school_taz: Optional[int] = Field(
        default=None,
        description='School traffic analysis zone identifier.',
        sa_column=Column(
            'school_taz',
            BigInteger,
            ForeignKey('LandUseAsimIn.TAZ'),
            nullable=True,
            index=True,
        ),
    )
    mar: Optional[int] = Field(
        default=None,
        description='Marital status code.',
        sa_column=Column('MAR', BigInteger, nullable=True),
    )
    edu: Optional[float] = Field(
        default=None,
        description='Education attainment code.',
        sa_column=Column('edu', Float, nullable=True),
    )


class AtlasResidential(SQLModel, table=True):
    __tablename__ = 'AtlasResidential'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    unit_id: Optional[int] = Field(
        default=None,
        description='Residential unit identifier (proposed primary key).',
        sa_column=Column('unit_id', BigInteger, primary_key=True, nullable=True, index=True),
    )
    block_id: Optional[str] = Field(
        default=None,
        description='Census block identifier for unit location.',
        sa_column=Column(
            'block_id',
            String,
            ForeignKey('AtlasBlocks.block_id'),
            nullable=True,
            index=True,
        ),
    )
    acs_18_rent: Optional[float] = Field(
        default=None,
        description='ACS 2018 rent estimate for the unit or block group.',
        sa_column=Column('ACS_18_rent', Float, nullable=True),
    )
    acs_13_value: Optional[float] = Field(
        default=None,
        description='ACS 2013 value estimate for the unit or block group.',
        sa_column=Column('ACS_13_value', Float, nullable=True),
    )
    lcm_county_id: Optional[str] = Field(
        default=None,
        description='County identifier used by land change modeling.',
        sa_column=Column('lcm_county_id', String, nullable=True),
    )
    year_built: Optional[int] = Field(
        default=None,
        description='Year the residential unit was built.',
        sa_column=Column('year_built', BigInteger, nullable=True),
    )
    building_type_id: Optional[int] = Field(
        default=None,
        description='Building type identifier for the unit.',
        sa_column=Column('building_type_id', BigInteger, nullable=True),
    )
    block_group_id: Optional[str] = Field(
        default=None,
        description='Census block group identifier for the unit.',
        sa_column=Column('block_group_id', String, nullable=True),
    )
    acs_13_rent: Optional[float] = Field(
        default=None,
        description='ACS 2013 rent estimate for the unit or block group.',
        sa_column=Column('ACS_13_rent', Float, nullable=True),
    )
    acs_18_value: Optional[float] = Field(
        default=None,
        description='ACS 2018 value estimate for the unit or block group.',
        sa_column=Column('ACS_18_value', Float, nullable=True),
    )


class HouseholdVAtlasOut(SQLModel, table=True):
    __tablename__ = 'HouseholdVAtlasOut'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    household_id: Optional[int] = Field(
        default=None,
        description='Household identifier for vehicle ownership output.',
        sa_column=Column(
            'household_id',
            BigInteger,
            ForeignKey('AtlasHousehold.household_id'),
            primary_key=True,
            nullable=True,
            index=True,
        ),
    )
    nvehicles: Optional[int] = Field(
        default=None,
        description='Number of vehicles for the household.',
        sa_column=Column('nvehicles', BigInteger, nullable=True),
    )
    year: Optional[int] = Field(
        default=None,
        description='Model year associated with the output record.',
        sa_column=Column('year', BigInteger, primary_key=True, nullable=True, index=True),
    )
    newhhflag: Optional[str] = Field(
        default=None,
        description='Indicator for newly created household in the model year.',
        sa_column=Column('newhhflag', String, nullable=True),
    )


class VehiclesAtlasOut(SQLModel, table=True):
    __tablename__ = 'VehiclesAtlasOut'
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    household_id: Optional[int] = Field(
        default=None,
        description='Household identifier associated with the vehicle.',
        sa_column=Column(
            'household_id',
            BigInteger,
            ForeignKey('AtlasHousehold.household_id'),
            primary_key=True,
            nullable=True,
            index=True,
        ),
    )
    vehicle_id: Optional[int] = Field(
        default=None,
        description='Vehicle identifier within the household.',
        sa_column=Column('vehicle_id', BigInteger, primary_key=True, nullable=True, index=True),
    )
    bodytype: Optional[str] = Field(
        default=None,
        description='Body type category for the vehicle.',
        sa_column=Column('bodytype', String, nullable=True),
    )
    pred_power: Optional[str] = Field(
        default=None,
        description='Predicted powertrain category.',
        sa_column=Column('pred_power', String, nullable=True),
    )
    ownlease: Optional[str] = Field(
        default=None,
        description='Ownership/lease status for the vehicle.',
        sa_column=Column('ownlease', String, nullable=True),
    )
    modelyear: Optional[int] = Field(
        default=None,
        description='Vehicle model year.',
        sa_column=Column('modelyear', BigInteger, nullable=True),
    )
    adopt_fuel: Optional[str] = Field(
        default=None,
        description='Adopted fuel type for the vehicle.',
        sa_column=Column('adopt_fuel', String, nullable=True),
    )
    adopt_veh: Optional[str] = Field(
        default=None,
        description='Vehicle technology adoption category.',
        sa_column=Column('adopt_veh', String, nullable=True),
    )
    acquire_year: Optional[str] = Field(
        default=None,
        description='Vehicle acquisition year.',
        sa_column=Column('acquire_year', String, nullable=True),
    )
    vehicle_tag: Optional[str] = Field(
        default=None,
        description='Vehicle tag/identifier label.',
        sa_column=Column('vehicle_tag', String, nullable=True),
    )
    year: Optional[int] = Field(
        default=None,
        description='Model year associated with the output record.',
        sa_column=Column('year', BigInteger, primary_key=True, nullable=True, index=True),
    )
    newhhflag: Optional[str] = Field(
        default=None,
        description='Indicator for newly created household in the model year.',
        sa_column=Column('newhhflag', String, nullable=True),
    )
    maindriver_id: Optional[str] = Field(
        default=None,
        description='Primary driver identifier for the vehicle.',
        sa_column=Column(
            'maindriver_id',
            String,
            ForeignKey('AtlasPersons.person_id'),
            nullable=True,
            index=True,
        ),
    )
    vintage_category: Optional[str] = Field(
        default=None,
        description='Vehicle vintage/age category.',
        sa_column=Column('vintage_category', String, nullable=True),
    )
