
region: austin
scenario: base
start_year: 2010
end_year: 2050
land_use_freq: 1
activity_demand_freq: 5
travel_model_freq: 5

land_use_image: mxndrwgrdnr/usim_block_model
activity_demand_image: mxdnrwgrdnr/activitysim
travel_model_image: beam/beam

land_use_bucket: austin-urbansim
activity_demand_bucket: austin-activitysim
travel_model_bucket: austin-skims

validation_metrics:
  - commute_dists
  - mode_shares
  - auto_ownership
  - density_gradients:
    - rent:
      - access:
        - var: employment
        - cost: minutes
        - levels:
          - 15
          - 45
    - jobs:
      - access:
        - var: employment
        - cost: minutes
        - levels:
          - 15
          - 45
    - population:
      - access:
        - var: employment
        - cost: minutes
        - levels:
          - 15
          - 45
