#########################################################################################################

############################
#     PILATES SETTINGS     #
############################

# scenario defs
region: austin
scenario: base
start_year: 2010
end_year: 2012
land_use_freq: 1
travel_model_freq: 1

# simulation platforms (comment out to turn off)
land_use_model: urbansim
travel_model: polaris
activity_demand_model:

# docker settings
docker_images:
  urbansim: mxndrwgrdnr/block_model_v2_pb
  beam: dimaopen/beam:0.8.6.3
  activitysim: mxndrwgrdnr/activitysim
  polaris:
docker_stdout: False
pull_latest: False

# misc pilates settings
skims_fname: campo_skims.hdf5
# skims_fname: 10.activitySimODSkims.UrbanSim.TAZ.Full.csv.gz

#########################################################################################################

###############################
#    SUB-PLATFORM SETTINGS    #
###############################

# URBANSIM
region_to_region_id:
  sfbay: "06197001"
  austin: "48197301"
usim_local_data_folder: pilates/urbansim/data/
usim_client_data_folder: /base/block_model_probaflow/data/
usim_formattable_input_file_name: "custom_mpo_{region_id}_model_data.h5"
usim_formattable_output_file_name: "model_data_{year}.h5"
usim_formattable_command: "-r {0} -i {1} -y {2} -f {3}"


# BEAM 
beam_config: gemini/activitysim-base-from-60k-input.conf
beam_local_input_folder: pilates/beam/production/
beam_local_output_folder: pilates/beam/beam_output/
beam_plans: gemini/activitysim-plans-base-2010-cut-60k/plans.csv.gz
beam_memory: "100g"
skim_zone_source_id_col: objectid
replan_iters: 0
replan_hh_sample_size: 0
replan_after: trip_scheduling  # resume asim after this step


# POLARIS
polaris_local_data_folder: pilates/polaris/data
polaris_skim_keys:
  base: 'auto_skims'
  t: 't4'  # 8-9am
  impedances:
    - ivtt
    - cost

# ACTIVITYSIM
household_sample_size: 0  # zero means no sampling, whole pop.
chunk_size: 6000000000
num_processes: 80
asim_local_input_folder: pilates/activitysim/data/
asim_local_output_folder: pilates/activitysim/output/
asim_formattable_command: "-y {0} -h {1} -n {2} -c {3}"
region_to_asim_subdir:
  austin: austin_mp 
  detroit: detroit 
  sfbay: bay_area
region_to_asim_bucket:
  austin: austin-activitysim
  detroit: detroit-activitysim
  sfbay: bayarea-activitysim
periods:
  - EA
  - AM
  - MD
  - PM
  - EV
transit_paths:
  - DRV_COM_WLK
  - DRV_HVY_WLK
  - DRV_LOC_WLK
  - DRV_LRF_WLK
  - DRV_EXP_WLK
  - WLK_COM_DRV   
  - WLK_HVY_DRV
  - WLK_LOC_DRV
  - WLK_LRF_DRV
  - WLK_EXP_DRV
  - WLK_COM_WLK
  - WLK_HVY_WLK
  - WLK_LOC_WLK
  - WLK_LRF_WLK
  - WLK_EXP_WLK
  - WLK_TRN_WLK
hwy_paths:
  - SOV
  - SOVTOLL
  - HOV2
  - HOV2TOLL
  - HOV3
  - HOV3TOLL
beam_asim_hwy_measure_map:
  TIME: TIME_minutes
  DIST: DIST_miles
  BTOLL: null
  VTOLL: VTOLL_FAR
beam_asim_transit_measure_map:
  WAIT: null
  TOTIVT: TOTIVT_IVT_minutes
  KEYIVT: KEYIVT_minutes
  FERRYIVT: FERRYIVT_minutes
  FAR: VTOLL_FAR
  DTIM: DTIM_minutes
  DDIST: DDIST_miles
  WAUX: WAUX_minutes
  WEGR: WEGR_minutes
  WACC: WACC_minutes
  IWAIT: null
  XWAIT: null
  BOARDS: BOARDS
  IVT: TOTIVT_IVT_minutes
asim_output_tables:
  prefix: final_
  tables:
    - checkpoints
    - land_use
    - households
    - persons
    - tours
    - trips
    - joint_tour_participants
    - plans


#########################################################################################################

################################
#    MISC. PILATES SETTINGS    #
################################

# GEOGRAPHY SETTINGS
FIPS:
  sfbay:
    state: "06"
    counties:
      - "001"
      - "013"
      - "041"
      - "055"
      - "075"
      - "081"
      - "085"
      - "095"
      - "097"
  austin:
    state: "48"
    counties:
      - "021"
      - "053"
      - "055"
      - "209"
      - "453"
      - "491"
local_crs:
  sfbay: EPSG:7131
  austin: EPSG:32140

# VALIDATION METRIC LIBRARY
validation_metrics:
  growth:
    - population
    - employment
    - residential_units
  commute_dists:
  mode_shares:
  auto_ownership:
  density_gradients:
    rent:
      access:
        var: employment
        cost: minutes
        levels:
          - 15
          - 45
    jobs:
      access:
        var: employment
        cost: minutes
        levels:
          - 15
          - 45
    population:
      access:
        var: employment
        cost: minutes
        levels:
          - 15
          - 45
