import abc
import logging
import subprocess
import docker
from abc import ABC
from typing import Dict, Optional, List, Tuple

from pilates.generic.records import RecordStore, ModelRunInfo
from pilates.utils.provenance import FileProvenanceTracker
from workflow_state import WorkflowState
from pilates.utils.container_utils import to_singularity_volumes, to_singularity_env

logger = logging.getLogger(__name__)


class GenericRunner(ABC):
    """
    A generic runner class that can be extended for specific models.
    """

    def __init__(self, model_name: str):
        self.model_name = model_name
        self.required_input_files = []
        self.required_output_files = []

    def check_required_input_files(self, inputStore: RecordStore) -> bool:
        # TODO: Implement a check for required input files. Requires Record.simple_name
        return True

    @staticmethod
    def get_model_and_image(settings: dict, model_type: str):
        manager = settings.get("container_manager")
        if manager == "docker":
            image_names = settings.get("docker_images", {})
        elif manager == "singularity":
            image_names = settings.get("singularity_images", {})
        else:
            raise ValueError(
                "Container Manager not specified (container_manager param in settings.yaml)"
            )

        model_name = settings.get(model_type)
        if not model_name:
            # If model type is optional (e.g., vehicle_ownership_model), return None
            optional_models = ["vehicle_ownership_model"]  # Add other optional models here
            if model_type in optional_models:
                return None, None
            else:
                raise ValueError(f"No model {model_type} specified in settings.")

        image_name = image_names.get(model_name)
        if not image_name:
            raise ValueError(
                f"No {manager} image specified for model '{model_name}' (model type: {model_type}). Check settings['{manager}_images']."
            )

        return model_name, image_name

    @abc.abstractmethod
    def run(self, store: RecordStore, state: WorkflowState) -> Tuple[RecordStore, ModelRunInfo]:
        """
        Do the model run

        Args:
            store (RecordStore): The input data generated by the preprocessor.
            state (WorkflowState): The workflow state.

        Returns:
            tuple: A tuple containing:
                - data (RecordStore): The raw output files that have been prepared to run the model
                - model_run_info (ModelRunInfo): Information about the model run
        """
        raise NotImplementedError("Subclasses should implement this method.")

    @staticmethod
    def run_container(
        client,
        settings: dict,
        image: str,
        volumes: dict,
        command: str,
        model_name: str,
        working_dir=None,
        environment=None,
        args=None,
    ) -> bool:
        """
        Executes container using docker or singularity

        Args:
            client: the docker client. If it's provided then docker is used, otherwise singularity is used
            settings: settings to get docker configuration
            image: the image to run
            volumes: a dictionary describing volume binding
            command: the command to run
            model_name: name of the model, used for stubs
            working_dir: the working directory inside the container
            environment: a dictionary that contains environment variables
            args: additional arguments to the command

        Returns:
            bool: True if the container/stub ran successfully (exit code 0), False otherwise.
        """
        if client:  # Docker client is available
            docker_stdout = settings.get("docker_stdout", False)
            logger.info("Running docker container: %s, command: %s", image, command)
            run_kwargs = {
                "volumes": volumes,
                "command": command,
                "stdout": docker_stdout,
                "stderr": True,  # Always capture stderr
                "detach": True,  # Run in detached mode to stream logs
            }
            if working_dir:
                run_kwargs["working_dir"] = working_dir
            if environment:
                run_kwargs["environment"] = environment
            if args:
                # Append args to command string for docker
                full_command = command + " " + " ".join(args)
                run_kwargs["command"] = full_command
                logger.info("Full docker command: %s", full_command)

            container = None
            try:
                container = client.containers.run(image, **run_kwargs)
                # Stream logs
                for line in container.logs(stream=True, stderr=True, stdout=docker_stdout):
                    # Decode bytes and print
                    try:
                        print(line.decode("utf-8").strip())
                    except UnicodeDecodeError:
                        print(line.strip())  # Print raw bytes if decoding fails

                # Wait for container to finish and get exit code
                result = container.wait()
                exit_code = result["StatusCode"]
                logger.info(
                    f"Docker container {image} finished with exit code: {exit_code}"
                )
                return exit_code == 0

            except docker.errors.ImageNotFound:
                logger.error(f"Docker image not found: {image}")
                return False
            except docker.errors.APIError as e:
                logger.error(f"Docker API error running container {image}: {e}")
                return False
            except Exception as e:
                logger.error(f"Unexpected error running docker container {image}: {e}")
                return False
            finally:
                if container:
                    try:
                        container.remove()
                        logger.debug(f"Removed container {container.id}")
                    except docker.errors.APIError as e:
                        logger.warning(f"Could not remove container {container.id}: {e}")

        else:  # Singularity
            import os
            for local_folder in volumes:
                # Ensure local directories exist for singularity binds
                os.makedirs(local_folder, exist_ok=True)

            singularity_volumes = to_singularity_volumes(volumes)
            # Construct the singularity command
            proc = (
                ["singularity", "run", "--cleanenv", "--writable-tmpfs"]
                + (["--env", to_singularity_env(environment)] if environment else [])
                + (["--pwd", working_dir] if working_dir else [])
                + ["-B", singularity_volumes, image]
                + (args if args else [])
                + command.split()
            )  # Split command string into list

            logger.info("Running singularity command: %s", " ".join(proc))

            # Check if using stubs
            if settings.get("use_stubs"):
                # Pass the full command string as config_name to the stub
                stub_cmd = [
                    "python",
                    os.path.join(
                        os.path.dirname(__file__), "..", "..", "tests", "stubs", "run_stub.py"
                    ),  # Use relative path for stub
                    "--model_name",
                    model_name,
                    "--cwd",
                    os.getcwd(),  # Pass current working directory of run.py
                    "--config_name",
                    " ".join(command),  # Pass the original command string
                ]
                logger.info(
                    f"Using stub for {model_name} ({image}). Running stub command: {' '.join(stub_cmd)}"
                )
                try:
                    result = subprocess.run(
                        stub_cmd, check=True, capture_output=True, text=True
                    )
                    print("Stub stdout:\n", result.stdout)
                    print("Stub stderr:\n", result.stderr)
                    logger.info(f"Stub for {model_name} finished successfully.")
                    return True  # Stub success is check=True
                except subprocess.CalledProcessError as e:
                    logger.error(
                        f"Stub for {model_name} failed with exit code {e.returncode}."
                    )
                    print("Stub stdout:\n", e.stdout)
                    print("Stub stderr:\n", e.stderr)
                    return False
                except FileNotFoundError:
                    logger.error(f"Stub script not found at {stub_cmd[2]}.")
                    return False
                except Exception as e:
                    logger.error(f"Unexpected error running stub for {model_name}: {e}")
                    return False

            else:  # Run actual singularity container
                try:
                    # Use subprocess.run to execute singularity command
                    result = subprocess.run(
                        proc, check=False
                    )  # Don't raise exception on non-zero exit code
                    logger.info(
                        f"Singularity container {image} finished with exit code: {result.returncode}"
                    )
                    return result.returncode == 0
                except FileNotFoundError:
                    logger.error(
                        f"Singularity command not found. Is Singularity installed and in your PATH?"
                    )
                    return False
                except Exception as e:
                    logger.error(
                        f"Unexpected error running singularity container {image}: {e}"
                    )
                    return False

    @staticmethod
    def initialize_docker_client(settings):
        land_use_model = settings.get("land_use_model", False)
        vehicle_ownership_model = settings.get("vehicle_ownership_model", False)  ## ATLAS
        activity_demand_model = settings.get("activity_demand_model", False)
        travel_model = settings.get("travel_model", False)
        models = [
            land_use_model,
            vehicle_ownership_model,
            activity_demand_model,
            travel_model,
        ]
        image_names = settings["docker_images"]
        pull_latest = settings.get("pull_latest", False)

        client = docker.from_env()
        if pull_latest:
            logger.info("Pulling from docker...")
            for model in models:
                if model:
                    image = image_names.get(model)  # Use .get for safety
                    if image is not None:
                        print("Pulling latest image for {0}".format(image))
                        try:
                            client.images.pull(image)
                        except docker.errors.ImageNotFound:
                            logger.error(f"Docker image {image} not found.")
                        except Exception as e:
                            logger.error(f"Error pulling docker image {image}: {e}")

        return client
