from __future__ import annotations

import abc
import logging
import os
import shlex
import shutil
import subprocess
from typing import TYPE_CHECKING, Optional, List, Union, Dict, Any

from pilates.config import PilatesConfig
from pilates.generic.model import Model

from abc import ABC

from pilates.generic.records import RecordStore
from pilates.utils import consist_runtime as cr
from pilates.workspace import Workspace
from workflow_state import WorkflowState
from pilates.utils.settings_helper import get as get_setting


logger = logging.getLogger(__name__)


class GenericRunner(ABC, Model):
    """
    A generic runner class that can be extended for specific models.
    """

    def __init__(
        self,
        model_name: str,
        state: "WorkflowState",
        major_stage: Optional["WorkflowState.Stage"] = None,  # new
    ):
        super().__init__(model_name, state, major_stage)  # new
        self.required_input_files = []
        self.required_output_files = []

    def setup_container_cache_dirs(self, settings: PilatesConfig):
        """
        Deprecated: Consist backends handle cache directory setup internally.
        Kept for backward compatibility with subclasses.
        """
        pass

    def check_required_input_files(self, inputStore: RecordStore) -> bool:
        # TODO: Implement a check for required input files. Requires Record.simple_name
        return True

    @staticmethod
    def get_model_and_image(settings: PilatesConfig, model_type: str):
        manager = settings.infrastructure.container_manager
        if manager == "docker":
            image_names = settings.infrastructure.docker_images
        elif manager == "singularity":
            image_names = settings.infrastructure.singularity_images
        else:
            raise ValueError(
                "Container Manager not specified (container_manager param in settings.yaml)"
            )

        # Map legacy model_type keys to their new paths under run.models
        model_name_map = {
            "land_use_model": settings.run.models.land_use,
            "travel_model": settings.run.models.travel,
            "activity_demand_model": settings.run.models.activity_demand,
            "vehicle_ownership_model": settings.run.models.vehicle_ownership,
        }

        model_name = model_name_map.get(model_type)

        # Fallback for custom or non-standard model types passed in tests
        if model_name is None:
            model_name = getattr(settings.run.models, model_type, None)

        if not model_name:
            optional_models = ["vehicle_ownership_model"]
            if model_type in optional_models:
                return None, None
            else:
                raise ValueError(f"No model {model_type} specified in settings.")

        image_name = image_names.get(model_name)
        if not image_name:
            raise ValueError(
                f"No {manager} image specified for model '{model_name}' (model type: {model_type}). Check settings for '{manager}_images'."
            )

        return model_name, image_name

    def run(
        self,
        store: RecordStore,
        workspace: Workspace,
    ) -> RecordStore:
        """
        Do the model run

        Args:
            store (RecordStore): The input data generated by the preprocessor.
            workspace (Workspace): The workspace.

        Returns:
            RecordStore: The raw output files that have been prepared to run the model.
        """
        self.state.set_sub_stage_progress("runner")
        return self._run(store, workspace)

    @abc.abstractmethod
    def _run(
        self,
        store: RecordStore,
        workspace: Workspace,
    ) -> RecordStore:
        """
        Do the model run.

        Subclasses should return a RecordStore of outputs without provenance side effects.

        Args:
            store (RecordStore): The input data generated by the preprocessor.
            workspace (Workspace): The workspace.

        Returns:
            RecordStore: The raw output files that have been prepared to run the model.
        """
        raise NotImplementedError("Subclasses should implement this method.")

    @staticmethod
    def run_container(
        client,
        settings: PilatesConfig,
        image: str,
        volumes: dict,
        command: str,
        model_name: str,
        working_dir=None,
        environment=None,
        args=None,
        input_artifacts: List[Union[str, Any]] = None,
        output_paths: List[str] = None,
        lineage_mode: str = None,
    ) -> bool:
        """
        Executes container with Consist if available, otherwise falls back to direct
        Docker/Singularity execution without provenance.
        """
        run_cfg = getattr(settings, "run", None)
        use_stubs = (
            getattr(run_cfg, "use_stubs", False) if run_cfg is not None else False
        )
        if use_stubs is True:
            logger.warning(
                "[%s] use_stubs=True; skipping container execution for image=%s",
                model_name,
                image,
            )
            return True

        mounts = GenericRunner._extract_mounts(volumes)
        consist_volumes = {host: container for host, container, _mode in mounts}

        # Handle command + args: Split if string, combine with args
        full_command_list = GenericRunner._build_full_command(command, args)

        # Determine settings from config
        backend_type = get_setting(
            settings, "infrastructure.container_manager", "docker"
        )
        pull_latest = get_setting(
            settings, "infrastructure.docker_config.pull_latest", False
        )
        docker_stdout = get_setting(
            settings, "infrastructure.docker_config.stdout", None
        )
        if docker_stdout is None:
            docker_stdout = get_setting(settings, "docker_stdout", False)

        if cr.consist_available(settings):
            tracker = cr.current_tracker()
            if not tracker:
                raise RuntimeError(
                    "A Consist tracker must be active for container execution. "
                    "Ensure the call occurs within a Consist scenario/run context."
                )
            try:
                from consist.integrations.containers import (
                    run_container as consist_run_container,
                )
            except ImportError as e:
                logger.error(
                    f"Consist container integration unavailable: {e}. Falling back to direct execution."
                )
            else:
                logger.info(f"[{model_name}] Delegating container execution to Consist")
                try:
                    return consist_run_container(
                        tracker=tracker,
                        run_id=f"{model_name}_container",
                        image=image,
                        command=full_command_list,
                        volumes=consist_volumes,
                        inputs=input_artifacts or [],
                        outputs=output_paths or [],
                        environment=environment or {},
                        working_dir=working_dir,
                        backend_type=backend_type,
                        pull_latest=pull_latest,
                        lineage_mode=lineage_mode,
                    )
                except Exception as e:
                    logger.error(
                        f"Consist container execution failed: {e}",
                        exc_info=True,
                    )

        logger.info(
            f"[{model_name}] Consist disabled/unavailable; using direct container execution."
        )
        return GenericRunner._run_container_direct(
            image=image,
            command=full_command_list,
            mounts=mounts,
            environment=environment or {},
            backend=backend_type,
            working_dir=working_dir,
            pull_latest=pull_latest,
            docker_stdout=docker_stdout,
        )

    @staticmethod
    def _build_full_command(command: Union[str, List[str]], args=None) -> List[str]:
        if isinstance(command, list):
            full_command_list = list(command)
        else:
            full_command_list = shlex.split(str(command))

        if args:
            if isinstance(args, list):
                full_command_list.extend(args)
            else:
                full_command_list.extend(shlex.split(str(args)))

        return full_command_list

    @staticmethod
    def _extract_mounts(volumes: dict) -> List[tuple]:
        mounts = []
        for host_path, mount_info in volumes.items():
            if isinstance(mount_info, dict):
                container_path = mount_info.get("bind", mount_info)
                mode = mount_info.get("mode", "rw")
            else:
                container_path = mount_info
                mode = "rw"

            if not isinstance(container_path, str):
                raise ValueError(
                    f"Invalid container path for mount {host_path!r}: {container_path!r}"
                )

            abs_host_path = os.path.abspath(host_path)
            mounts.append((abs_host_path, container_path, mode))
        return mounts

    @staticmethod
    def _run_container_direct(
        image: str,
        command: List[str],
        mounts: List[tuple],
        environment: Dict[str, str],
        backend: str,
        working_dir: Optional[str],
        pull_latest: bool,
        docker_stdout: bool,
    ) -> bool:
        if backend == "docker":
            return GenericRunner._run_docker_container(
                image=image,
                command=command,
                mounts=mounts,
                environment=environment,
                working_dir=working_dir,
                pull_latest=pull_latest,
                docker_stdout=docker_stdout,
            )
        if backend == "singularity":
            return GenericRunner._run_singularity_container(
                image=image,
                command=command,
                mounts=mounts,
                environment=environment,
                working_dir=working_dir,
            )

        raise ValueError(f"Unknown container backend: {backend}")

    @staticmethod
    def _run_docker_container(
        image: str,
        command: List[str],
        mounts: List[tuple],
        environment: Dict[str, str],
        working_dir: Optional[str],
        pull_latest: bool,
        docker_stdout: bool,
    ) -> bool:
        if pull_latest:
            pull_cmd = ["docker", "pull", image]
            logger.info(f"Pulling Docker image {image}")
            subprocess.run(pull_cmd, check=True)

        docker_cmd = ["docker", "run", "--rm"]
        if working_dir:
            docker_cmd.extend(["-w", working_dir])

        for host_path, container_path, mode in mounts:
            docker_cmd.extend(["-v", f"{host_path}:{container_path}:{mode}"])

        for key, value in (environment or {}).items():
            docker_cmd.extend(["-e", f"{key}={value}"])

        docker_cmd.append(image)
        docker_cmd.extend(command)

        logger.info(f"Running Docker container: {' '.join(docker_cmd)}")
        try:
            subprocess.run(
                docker_cmd,
                check=True,
                capture_output=not docker_stdout,
                text=True,
            )
            return True
        except subprocess.CalledProcessError as e:
            logger.error(f"Docker execution failed: {e}", exc_info=True)
            return False

    @staticmethod
    def _run_singularity_container(
        image: str,
        command: List[str],
        mounts: List[tuple],
        environment: Dict[str, str],
        working_dir: Optional[str],
    ) -> bool:
        runtime = "apptainer" if shutil.which("apptainer") else "singularity"

        bind_args = []
        for host_path, container_path, mode in mounts:
            bind_args.extend(["-B", f"{host_path}:{container_path}:{mode}"])

        sing_cmd = [runtime, "run", "--cleanenv"]
        if working_dir:
            sing_cmd.extend(["--pwd", working_dir])
        sing_cmd.extend(bind_args)
        sing_cmd.append(image)
        sing_cmd.extend(command)

        env = dict(os.environ)
        for key, value in (environment or {}).items():
            if runtime == "apptainer":
                env[f"APPTAINERENV_{key}"] = value
            else:
                env[f"SINGULARITYENV_{key}"] = value

        logger.info(f"Running Singularity container: {' '.join(sing_cmd)}")
        try:
            subprocess.run(
                sing_cmd,
                check=True,
                env=env,
            )
            return True
        except subprocess.CalledProcessError as e:
            logger.error(f"Singularity execution failed: {e}", exc_info=True)
            return False

    @staticmethod
    def initialize_docker_client(settings):
        # Deprecated: Consist handles backend initialization
        return None
