"""
Compatibility exports for workflow artifact keys.

Prefer importing `ArtifactKeys` from `pilates.workflows.artifact_keys`.
"""

from pilates.workflows.artifact_keys import ArtifactKeys as K

USIM_DATASTORE_H5 = K.USIM_DATASTORE_H5
USIM_H5_UPDATED = K.USIM_H5_UPDATED
USIM_MUTABLE_DATA_DIR = K.USIM_MUTABLE_DATA_DIR
USIM_FORECAST_OUTPUT = K.USIM_FORECAST_OUTPUT
USIM_INPUT_MERGED_PREFIX = K.USIM_INPUT_MERGED_PREFIX
USIM_INPUT_ARCHIVE_PREFIX = K.USIM_INPUT_ARCHIVE_PREFIX

ATLAS_OUTPUT_DIR = K.ATLAS_OUTPUT_DIR
ATLAS_VEHICLES2_INPUT = K.ATLAS_VEHICLES2_INPUT

ASIM_MUTABLE_DATA_DIR = K.ASIM_MUTABLE_DATA_DIR
ASIM_OUTPUT_DIR = K.ASIM_OUTPUT_DIR

BEAM_OUTPUT_DIR = K.BEAM_OUTPUT_DIR
BEAM_MUTABLE_DATA_DIR = K.BEAM_MUTABLE_DATA_DIR
LINKSTATS = K.LINKSTATS
BEAM_PLANS_OUT = K.BEAM_PLANS_OUT
BEAM_OUTPUT_PLANS_XML = K.BEAM_OUTPUT_PLANS_XML
BEAM_EXPERIENCED_PLANS_XML = K.BEAM_EXPERIENCED_PLANS_XML
BEAM_OUTPUT_EXPERIENCED_PLANS_XML = K.BEAM_OUTPUT_EXPERIENCED_PLANS_XML
BEAM_R5_OSM_FILE = K.BEAM_R5_OSM_FILE

# ActivitySim preprocess inputs
ASIM_LAND_USE_IN = K.ASIM_LAND_USE_IN
ASIM_HOUSEHOLDS_IN = K.ASIM_HOUSEHOLDS_IN
ASIM_PERSONS_IN = K.ASIM_PERSONS_IN
ASIM_OMX_SKIMS = K.ASIM_OMX_SKIMS

# BEAM preprocess inputs
BEAM_PLANS_IN = K.BEAM_PLANS_IN
BEAM_HOUSEHOLDS_IN = K.BEAM_HOUSEHOLDS_IN
BEAM_PERSONS_IN = K.BEAM_PERSONS_IN
LINKSTATS_WARMSTART = K.LINKSTATS_WARMSTART

ZARR_SKIMS = K.ZARR_SKIMS
FINAL_SKIMS_OMX = K.FINAL_SKIMS_OMX
