from typing import Tuple
import logging
import os

from pilates.generic.runner import GenericRunner
from pilates.generic.records import RecordStore, ModelRunInfo
from pilates.workspace import Workspace
from workflow_state import WorkflowState
from pilates.utils.provenance import FileProvenanceTracker

logger = logging.getLogger(__name__)




class UrbansimRunner(GenericRunner):
    """
    Runner for the UrbanSim land use model.
    This class is responsible for running the UrbanSim containerized model.
    All preprocessing and postprocessing should be handled outside this method,
    following the BEAM/ActivitySim/ATLAS pattern.
    """

    def __init__(self, model_name: str, state: "WorkflowState", provenance_tracker: FileProvenanceTracker):
        super().__init__(model_name, state, provenance_tracker)
        self.required_input_files = ["usim_data"]

    def get_usim_docker_vols(self, output_dir=None):
        settings = self.state.full_settings
        usim_remote_data_folder = settings["usim_client_data_folder"]
        if output_dir is None:
            output_dir = settings[
                "usim_local_data_input_folder"
            ]  # This seems wrong, should be mutable output dir
            logger.warning(
                "get_usim_docker_vols called without output_dir, using usim_local_data_input_folder. Check logic."
            )
        usim_local_mutable_data_folder = os.path.abspath(output_dir)
        usim_docker_vols = {
            usim_local_mutable_data_folder: {"bind": usim_remote_data_folder, "mode": "rw"}
        }
        return usim_docker_vols

    def get_usim_cmd(self):
        settings = self.state.full_settings
        year = self.state.current_year
        forecast_year = self.state.forecast_year
        region = settings["region"]
        region_id = settings["region_to_region_id"][region]
        land_use_freq = settings["land_use_freq"]
        skims_source = settings["travel_model"]
        formattable_usim_cmd = settings["usim_formattable_command"]
        usim_cmd = formattable_usim_cmd.format(
            region_id, year, forecast_year, land_use_freq, skims_source
        )
        return usim_cmd

    def run(
        self,
        store: RecordStore,
        workspace: Workspace,
    ) -> Tuple[RecordStore, ModelRunInfo]:
        """
        Executes the UrbanSim model run.

        Args:
            store (RecordStore): The input data generated by the preprocessor.
            workspace (Workspace): The workspace object for path management.

        Returns:
            tuple: A tuple containing:
                - data (RecordStore): The raw output files that have been prepared to run the model
                - model_run_info (ModelRunInfo): Information about the model run

        Notes:
            - All preprocessing and postprocessing should be handled outside this method.
            - This method only runs the UrbanSim container and records provenance for the run.
        """
        logger.info(
            "[UrbansimRunner] Starting UrbanSim model run for year %s",
            self.state.current_year,
        )
        settings = self.state.full_settings
        forecast_year = self.state.forecast_year

        # Prepare output file path
        usim_output_store_name = settings["usim_formattable_output_file_name"].format(
            year=forecast_year
        )
        usim_datastore_fpath = os.path.join(
            workspace.get_usim_mutable_data_dir(), usim_output_store_name
        )

        # 1. PARSE SETTINGS
        land_use_model, land_use_image = self.get_model_and_image(
            settings, "land_use_model"
        )
        usim_docker_vols = self.get_usim_docker_vols(
            settings
        )
        usim_cmd = self.get_usim_cmd()

        # TODO: Add logic to actually run the UrbanSim container here, similar to AtlasRunner/BeamRunner.
        # For now, just record the output file if it exists.

        output_records = []
        if os.path.exists(usim_datastore_fpath):
            output_rec = self.provenance_tracker.record_output_file(
                self.model_name,
                usim_datastore_fpath,
                year=forecast_year,
                description="UrbanSim forecast output data",
                model_run_id=None,  # To be filled in later
            )
            if output_rec:
                output_records.append(output_rec)
            logger.info(
                f"[UrbansimRunner] Recorded UrbanSim output file: {usim_datastore_fpath}"
            )
        else:
            logger.error(
                f"[UrbansimRunner] UrbanSim output file not found at {usim_datastore_fpath}"
            )

        # Return empty RecordStore and None for ModelRunInfo for now
        # In the future, this should return the actual outputs and run info
        return RecordStore(), ModelRunInfo()
