from typing import Optional, Dict, Any
import logging
import os

from pilates.config import PilatesConfig
from pilates.generic.runner import GenericRunner
from pilates.generic.records import RecordStore, FileRecord
from pilates.urbansim import postprocessor as usim_post
from pilates.workspace import Workspace
from workflow_state import WorkflowState
from pilates.utils.provenance import FileProvenanceTracker

logger = logging.getLogger(__name__)


class UrbansimRunner(GenericRunner):
    """
    Runner for the UrbanSim land use model.
    This class is responsible for running the UrbanSim containerized model.
    """

    @staticmethod
    def expected_inputs(
        settings: PilatesConfig, state: "WorkflowState", workspace: Workspace
    ) -> Dict[str, Any]:
        """
        Declare the input paths/artifacts this runner expects from the workflow.
        """
        usim_data_dir = workspace.get_usim_mutable_data_dir()
        if state.is_start_year():
            usim_input_fname = usim_post.get_usim_datastore_fname(
                settings, io="input"
            )
        else:
            usim_input_fname = usim_post.get_usim_datastore_fname(
                settings, io="output", year=state.forecast_year
            )
        usim_input_path = os.path.join(usim_data_dir, usim_input_fname)
        return {
            "usim_mutable_data_dir": usim_data_dir,
            "usim_datastore_h5": usim_input_path if os.path.exists(usim_input_path) else None,
        }

    @staticmethod
    def expected_outputs(
        settings: PilatesConfig, state: "WorkflowState", workspace: Workspace
    ) -> Dict[str, Any]:
        """
        Declare the output paths/artifacts this runner produces.
        """
        usim_output_fname = usim_post.get_usim_datastore_fname(
            settings, io="output", year=state.forecast_year
        )
        usim_output_path = os.path.join(
            workspace.get_usim_mutable_data_dir(), usim_output_fname
        )
        return {
            "usim_datastore_h5": usim_output_path,
        }

    def __init__(
        self,
        model_name: str,
        state: "WorkflowState",
        provenance_tracker: FileProvenanceTracker,
        major_stage: Optional["WorkflowState.Stage"] = None,
    ):
        super().__init__(model_name, state, provenance_tracker, major_stage)
        self.required_input_files = ["usim_data"]

    def get_usim_docker_vols(self, output_dir: str) -> dict:
        """Constructs the volume mappings for the UrbanSim Docker container.

        Args:
            output_dir (str): The absolute path to the mutable data directory for UrbanSim.

        Returns:
            dict: A dictionary of volume mappings for the Docker container.
        """
        settings = self.state.full_settings
        usim_remote_data_folder = settings.urbansim.client_data_folder
        usim_local_mutable_data_folder = os.path.abspath(output_dir)
        usim_docker_vols = {
            usim_local_mutable_data_folder: {
                "bind": usim_remote_data_folder,
                "mode": "rw",
            }
        }
        return usim_docker_vols

    def get_usim_cmd(self) -> str:
        """Constructs the command to be executed inside the UrbanSim container.

        Returns:
            str: The formatted command string.
        """
        settings = self.state.full_settings
        year = self.state.current_year
        forecast_year = self.state.forecast_year
        region = settings.run.region
        region_id = settings.urbansim.region_mappings["region_to_region_id"][region]
        land_use_freq = settings.run.land_use_freq
        skims_source = settings.run.models.travel
        formattable_usim_cmd = settings.urbansim.command_template
        usim_cmd = formattable_usim_cmd.format(
            region_id, year, forecast_year, land_use_freq, skims_source
        )
        return usim_cmd

    def _run(
        self,
        store: RecordStore,
        workspace: Workspace,
        model_run_hash: Optional[str] = None,
    ) -> RecordStore:
        """
        Executes the UrbanSim model run.

        Args:
            store (RecordStore): The input data generated by the preprocessor.
            workspace (Workspace): The workspace object for path management.
            model_run_hash (Optional[str]): An optional hash for the model run.
                If not provided, a new one will be created.

        Returns:
            RecordStore: The raw output files from the model run.
        """
        logger.info(
            "[UrbansimRunner] Starting UrbanSim model run for year %s",
            self.state.current_year,
        )
        settings = self.state.full_settings
        forecast_year = self.state.forecast_year

        # Prepare output file path
        usim_output_store_name = settings.urbansim.output_file_template.format(
            year=forecast_year
        )
        usim_datastore_fpath = os.path.join(
            workspace.get_usim_mutable_data_dir(), usim_output_store_name
        )

        # Get container configuration
        land_use_model, land_use_image = self.get_model_and_image(
            settings, "land_use_model"
        )
        usim_docker_vols = self.get_usim_docker_vols(
            workspace.get_usim_mutable_data_dir()
        )
        usim_cmd = self.get_usim_cmd()

        # Initialize container client
        client = None

        # 1. EXTRACT INPUTS FOR CONSIST TRACKING
        input_paths = [r.file_path for r in store.all_records()]

        # Execute container
        try:
            success = self.run_container(
                client=client,
                settings=settings,
                image=land_use_image,
                volumes=usim_docker_vols,
                command=usim_cmd,
                model_name=self.model_name,
                working_dir=settings.urbansim.client_base_folder,
                # 2. PASS INPUTS
                input_artifacts=input_paths,
                # 3. OUTPUTS ALREADY CORRECT
                output_paths=[usim_datastore_fpath],
            )

            if not success:
                logger.error("UrbanSim container execution failed")
                raise RuntimeError("UrbanSim container execution failed")

        except Exception as e:
            logger.error(f"UrbanSim container execution error: {e}")
            raise

        # Collect outputs
        output_records = []
        if os.path.exists(usim_datastore_fpath):
            output_rec = FileRecord(
                file_path=usim_datastore_fpath,
                year=forecast_year,
                short_name="usim_forecast_output",
                description="UrbanSim forecast output data",
            )
            output_records.append(output_rec)
            logger.info(
                f"[UrbansimRunner] Recorded UrbanSim output file: {usim_datastore_fpath}"
            )
        else:
            logger.error(
                f"[UrbansimRunner] UrbanSim output file not found at {usim_datastore_fpath}"
            )
            raise RuntimeError(
                f"UrbanSim output file not found at {usim_datastore_fpath}"
            )

        return RecordStore(recordList=output_records)
