from typing import Tuple, Optional
import logging
import os

from pilates.generic.runner import GenericRunner
from pilates.generic.records import RecordStore, ModelRunInfo
from pilates.workspace import Workspace
from workflow_state import WorkflowState
from pilates.utils.provenance import FileProvenanceTracker

logger = logging.getLogger(__name__)


class UrbansimRunner(GenericRunner):
    """
    Runner for the UrbanSim land use model.
    This class is responsible for running the UrbanSim containerized model.
    """

    def __init__(
        self,
        model_name: str,
        state: "WorkflowState",
        provenance_tracker: FileProvenanceTracker,
        major_stage: Optional["WorkflowState.Stage"] = None,
    ):
        super().__init__(model_name, state, provenance_tracker, major_stage)
        self.required_input_files = ["usim_data"]

    def get_usim_docker_vols(self, output_dir: str) -> dict:
        """Constructs the volume mappings for the UrbanSim Docker container.

        Args:
            output_dir (str): The absolute path to the mutable data directory for UrbanSim.

        Returns:
            dict: A dictionary of volume mappings for the Docker container.
        """
        settings = self.state.full_settings
        usim_remote_data_folder = settings["usim_client_data_folder"]
        usim_local_mutable_data_folder = os.path.abspath(output_dir)
        usim_docker_vols = {
            usim_local_mutable_data_folder: {
                "bind": usim_remote_data_folder,
                "mode": "rw",
            }
        }
        return usim_docker_vols

    def get_usim_cmd(self) -> str:
        """Constructs the command to be executed inside the UrbanSim container.

        Returns:
            str: The formatted command string.
        """
        settings = self.state.full_settings
        year = self.state.current_year
        forecast_year = self.state.forecast_year
        region = settings["region"]
        region_id = settings["region_to_region_id"][region]
        land_use_freq = settings["land_use_freq"]
        skims_source = settings["travel_model"]
        formattable_usim_cmd = settings["usim_formattable_command"]
        usim_cmd = formattable_usim_cmd.format(
            region_id, year, forecast_year, land_use_freq, skims_source
        )
        return usim_cmd

    def _run(
        self,
        store: RecordStore,
        workspace: Workspace,
        model_run_hash: Optional[str] = None,
    ) -> Tuple[RecordStore, ModelRunInfo]:
        """
        Executes the UrbanSim model run.

        Args:
            store (RecordStore): The input data generated by the preprocessor.
            workspace (Workspace): The workspace object for path management.
            model_run_hash (Optional[str]): An optional hash for the model run.
                If not provided, a new one will be created.

        Returns:
            tuple: A tuple containing:
                - RecordStore: The raw output files from the model run.
                - ModelRunInfo: Information about the model run.
        """
        logger.info(
            "[UrbansimRunner] Starting UrbanSim model run for year %s",
            self.state.current_year,
        )
        settings = self.state.full_settings
        forecast_year = self.state.forecast_year

        # Start provenance tracking for this run if no hash is provided
        if model_run_hash is None:
            model_run_hash = self.provenance_tracker.start_model_run(
                self.model_name,
                self.state.current_year,
                self.state.current_inner_iter,
                description="UrbanSim land use model run",
                inputs=store,
            )

        # Prepare output file path
        usim_output_store_name = settings["usim_formattable_output_file_name"].format(
            year=forecast_year
        )
        usim_datastore_fpath = os.path.join(
            workspace.get_usim_mutable_data_dir(), usim_output_store_name
        )

        # Get container configuration
        land_use_model, land_use_image = self.get_model_and_image(
            settings, "land_use_model"
        )
        usim_docker_vols = self.get_usim_docker_vols(
            workspace.get_usim_mutable_data_dir()
        )
        usim_cmd = self.get_usim_cmd()

        # Initialize container client
        client = None
        if settings.get("container_manager") == "docker":
            try:
                client = self.initialize_docker_client(settings)
            except Exception as e:
                logger.error(f"Failed to initialize Docker client: {e}")
                self.provenance_tracker.complete_model_run(model_run_hash, status="failed")
                raise

        # Execute container
        try:
            success = self.run_container(
                client=client,
                settings=settings,
                image=land_use_image,
                volumes=usim_docker_vols,
                command=usim_cmd,
                model_name=self.model_name,
                working_dir=settings.get("usim_client_base_folder", "/app"),
            )

            if not success:
                logger.error("UrbanSim container execution failed")
                self.provenance_tracker.complete_model_run(model_run_hash, status="failed")
                run_info = self.provenance_tracker.run_info.model_runs.get(model_run_hash)
                return RecordStore(), run_info

        except Exception as e:
            logger.error(f"UrbanSim container execution error: {e}")
            self.provenance_tracker.complete_model_run(model_run_hash, status="failed")
            run_info = self.provenance_tracker.run_info.model_runs.get(model_run_hash)
            raise

        # Collect outputs
        output_records = []
        if os.path.exists(usim_datastore_fpath):
            output_rec = self.provenance_tracker.record_output_file(
                self.model_name,
                usim_datastore_fpath,
                year=forecast_year,
                description="UrbanSim forecast output data",
                model_run_id=model_run_hash,
                state=self.state,
            )
            if output_rec:
                output_records.append(output_rec)
            logger.info(
                f"[UrbansimRunner] Recorded UrbanSim output file: {usim_datastore_fpath}"
            )
        else:
            logger.error(
                f"[UrbansimRunner] UrbanSim output file not found at {usim_datastore_fpath}"
            )
            self.provenance_tracker.complete_model_run(model_run_hash, status="failed")
            return RecordStore(), ModelRunInfo(model=self.model_name, year=self.state.current_year)

        # Get the model run info object to return
        run_info = self.provenance_tracker.run_info.model_runs.get(model_run_hash)

        return RecordStore(recordList=output_records), run_info
