from pathlib import Path
from typing import Dict, Any
import logging
import os

from pilates.atlas.outputs import AtlasPreprocessOutputs, AtlasRunOutputs
from pilates.config import PilatesConfig
from pilates.generic.runner import GenericRunner
from pilates.workspace import Workspace
from workflow_state import WorkflowState


logger = logging.getLogger(__name__)


## Atlas vehicle ownership model volume mount defintion, equivalent to
## docker run -v atlas_host_input_folder:atlas_container_input_folder
def get_atlas_docker_vols(settings, workspace: Workspace):
    atlas_host_input_folder = workspace.get_atlas_mutable_input_dir()
    atlas_host_output_folder = workspace.get_atlas_output_dir()

    atlas_container_input_folder = os.path.abspath(
        settings.atlas.container_input_folder
    )
    atlas_container_output_folder = os.path.abspath(
        settings.atlas.container_output_folder
    )
    atlas_docker_vols = {
        atlas_host_input_folder: {  ## source location, aka "local"
            "bind": atlas_container_input_folder,  ## destination loc, aka "remote", "client"
            "mode": "rw",
        },
        atlas_host_output_folder: {"bind": atlas_container_output_folder, "mode": "rw"},
    }
    return atlas_docker_vols


## For Atlas container command
def get_atlas_cmd(
    settings,
    freq,
    output_year,
    npe,
    nsample,
    beamac,
    mod,
    adscen,
    rebfactor,
    taxfactor,
    discIncent,
):
    basedir = settings.atlas.basedir
    codedir = settings.atlas.codedir
    formattable_atlas_cmd = settings.atlas.command_template
    atlas_cmd = formattable_atlas_cmd.format(
        freq,
        output_year,
        npe,
        nsample,
        basedir,
        codedir,
        beamac,
        mod,
        adscen,
        rebfactor,
        taxfactor,
        discIncent,
    )
    return atlas_cmd


class AtlasRunner(GenericRunner):
    """
    Runner for the ATLAS vehicle ownership model.
    This class is responsible for running the ATLAS containerized model.
    All preprocessing and postprocessing should be handled outside this method,
    following the BEAM/ActivitySim pattern.
    """

    @staticmethod
    def expected_inputs(
        settings: PilatesConfig, state: "WorkflowState", workspace: Workspace
    ) -> Dict[str, Any]:
        """
        Declare the input paths/artifacts this runner expects from the workflow.
        """
        atlas_input_dir = workspace.get_atlas_mutable_input_dir()
        if state.is_start_year():
            region = settings.run.region
            region_id = settings.urbansim.region_mappings["region_to_region_id"][region]
            usim_datastore_fname = settings.urbansim.input_file_template.format(
                region_id=region_id
            )
        else:
            usim_datastore_fname = settings.urbansim.output_file_template.format(
                year=state.forecast_year
            )
        usim_datastore_h5 = os.path.join(
            workspace.get_usim_mutable_data_dir(), usim_datastore_fname
        )
        return {
            "atlas_mutable_input_dir": atlas_input_dir,
            "usim_datastore_h5": (
                usim_datastore_h5 if os.path.exists(usim_datastore_h5) else None
            ),
        }

    @staticmethod
    def expected_outputs(
        settings: PilatesConfig, state: "WorkflowState", workspace: Workspace
    ) -> Dict[str, Any]:
        """
        Declare the output paths/artifacts this runner produces.

        Notes
        -----
        Output keys
            - ``atlas_output_dir``: ATLAS output directory for the run.
        Related docs
            - See `pilates/atlas/inputs.py` for the corresponding input
              descriptions used by ATLAS and downstream models.
        """
        atlas_output_dir = workspace.get_atlas_output_dir()
        return {
            "atlas_output_dir": atlas_output_dir,
        }

    def __init__(
        self,
        model_name: str,
        state: "WorkflowState",
    ):
        super().__init__(model_name, state)

    def _run(
        self,
        inputs: AtlasPreprocessOutputs,
        workspace: Workspace,
    ) -> AtlasRunOutputs:
        """
        Executes the ATLAS model run.

        Args:
            inputs (AtlasPreprocessOutputs): Typed inputs generated by the preprocessor.
            workspace (Workspace): The workspace object for path management.

        Returns:
            AtlasRunOutputs: The raw output files that have been prepared to run the model.

        Notes:
            - All preprocessing and postprocessing should be handled outside this method.
            - This method only runs the ATLAS container and records provenance for the run.
        """
        logger.info(
            "[AtlasRunner] Starting ATLAS model run for year %s",
            self.state.current_year,
        )
        settings = self.state.full_settings

        # Get container configuration
        vehicle_ownership_model, atlas_image = self.get_model_and_image(
            settings, "vehicle_ownership_model"
        )

        atlas_docker_vols = get_atlas_docker_vols(settings, workspace)
        freq = settings.run.vehicle_ownership_freq
        npe = settings.atlas.num_processes
        sample_size = settings.atlas.sample_size
        # BEAMAC is an integer flag that controls accessibility calculation
        # 0 = no accessibility calculation
        # 1 = use BEAM skims to calculate accessibility
        # 2 = use BEAM skims to calculate accessibility, but only for the first year
        beamac = settings.atlas.beamac
        mod = settings.atlas.mod
        adscen = settings.atlas.adscen
        rebfactor = settings.atlas.rebfactor
        taxfactor = settings.atlas.taxfactor
        discIncent = settings.atlas.discIncent
        atlas_cmd = get_atlas_cmd(
            settings,
            freq,
            self.state.forecast_year,
            npe,
            sample_size,
            beamac,
            mod,
            adscen,
            rebfactor,
            taxfactor,
            discIncent,
        )

        # Initialize container client
        client = None

        # Execute container
        atlas_output_dir = workspace.get_atlas_output_dir()
        output_year = self.state.forecast_year
        expected_output_filenames = [
            f"householdv_{output_year}.csv",
            f"vehicles_{output_year}.csv",
        ]
        # Create full paths for Consist tracking
        expected_output_paths = [
            os.path.join(atlas_output_dir, f) for f in expected_output_filenames
        ]

        input_paths = [str(path) for _, path, _ in inputs._iter_record_items()]

        # Execute container
        try:
            logger.info(
                "[AtlasRunner] Running Atlas vehicle ownership model container for year %s",
                self.state.current_year,
            )
            max_retries = settings.atlas.max_retries
            success = False
            last_error = None

            for i in range(max_retries):
                try:
                    success = self.run_container(
                        client=client,
                        settings=settings,
                        image=atlas_image,
                        volumes=atlas_docker_vols,
                        command=atlas_cmd,
                        model_name=self.model_name,
                        working_dir="/",
                        # PASS INPUTS HERE
                        input_artifacts=input_paths,
                        # Canonical ATLAS outputs are logged by workflow step records
                        # using short names without file extensions. Avoid container-
                        # level output logging to prevent duplicate artifacts like
                        # householdv_2023 and householdv_2023.csv.
                        output_paths=None,
                        lineage_mode="none",
                    )
                    last_error = None
                except Exception as exc:
                    last_error = exc
                    success = False
                    logger.error(
                        "ATLAS container execution failed in attempt %s/%s: %s",
                        i + 1,
                        max_retries,
                        exc,
                    )
                    continue

                if not success:
                    logger.error(f"ATLAS container execution failed in attempt {i + 1}")
                else:
                    logger.info(
                        f"ATLAS container execution succeeded in attempt {i + 1}"
                    )
                    break

            if not success:
                if last_error is not None:
                    raise RuntimeError(
                        "ATLAS container execution failed after all retry attempts"
                    ) from last_error
                raise RuntimeError(
                    "ATLAS container execution failed after all retry attempts"
                )

        except Exception as e:
            logger.error(f"ATLAS container execution error: {e}")
            raise

        # 1. Define Expected Outputs EARLY (so we can pass to Consist)
        raw_outputs = {}
        missing_outputs = []
        for output_path in expected_output_paths:
            if os.path.exists(output_path):
                # Extract filename for short_name
                fname = os.path.basename(output_path)
                raw_outputs[fname.replace(".csv", "")] = Path(output_path)
            else:
                missing_outputs.append(output_path)

        if missing_outputs:
            preview = ", ".join(missing_outputs)
            raise RuntimeError(
                "ATLAS run did not produce required current-year outputs: "
                f"{preview}"
            )

        logger.info(
            "[AtlasRunner] ATLAS model run complete for year %s (outputs=%d)",
            self.state.current_year,
            len(raw_outputs),
        )

        return AtlasRunOutputs(
            atlas_output_dir=Path(atlas_output_dir),
            raw_outputs=raw_outputs,
        )

    def run(
        self,
        inputs: AtlasPreprocessOutputs,
        workspace: Workspace,
    ) -> AtlasRunOutputs:
        if not isinstance(inputs, AtlasPreprocessOutputs):
            raise TypeError("AtlasRunner.run expects AtlasPreprocessOutputs")
        self.state.set_sub_stage_progress("runner")
        return self._run(inputs, workspace)
