from typing import Optional
import logging
import os

from pilates.generic.runner import GenericRunner
from pilates.generic.records import RecordStore
from pilates.workspace import Workspace
from workflow_state import WorkflowState
from pilates.utils.provenance import FileProvenanceTracker


logger = logging.getLogger(__name__)


## Atlas vehicle ownership model volume mount defintion, equivalent to
## docker run -v atlas_host_input_folder:atlas_container_input_folder
def get_atlas_docker_vols(settings, workspace: Workspace):
    atlas_host_input_folder = workspace.get_atlas_mutable_input_dir()
    atlas_host_output_folder = workspace.get_atlas_output_dir()

    atlas_container_input_folder = os.path.abspath(
        settings.atlas.container_input_folder
    )
    atlas_container_output_folder = os.path.abspath(
        settings.atlas.container_output_folder
    )
    atlas_docker_vols = {
        atlas_host_input_folder: {  ## source location, aka "local"
            "bind": atlas_container_input_folder,  ## destination loc, aka "remote", "client"
            "mode": "rw",
        },
        atlas_host_output_folder: {"bind": atlas_container_output_folder, "mode": "rw"},
    }
    return atlas_docker_vols


## For Atlas container command
def get_atlas_cmd(
    settings,
    freq,
    output_year,
    npe,
    nsample,
    beamac,
    mod,
    adscen,
    rebfactor,
    taxfactor,
    discIncent,
):
    basedir = settings.atlas.basedir
    codedir = settings.atlas.codedir
    formattable_atlas_cmd = settings.atlas.command_template
    atlas_cmd = formattable_atlas_cmd.format(
        freq,
        output_year,
        npe,
        nsample,
        basedir,
        codedir,
        beamac,
        mod,
        adscen,
        rebfactor,
        taxfactor,
        discIncent,
    )
    return atlas_cmd


class AtlasRunner(GenericRunner):
    """
    Runner for the ATLAS vehicle ownership model.
    This class is responsible for running the ATLAS containerized model.
    All preprocessing and postprocessing should be handled outside this method,
    following the BEAM/ActivitySim pattern.
    """

    def __init__(
        self,
        model_name: str,
        state: "WorkflowState",
        provenance_tracker: FileProvenanceTracker,
        major_stage: Optional["WorkflowState.Stage"] = None,
    ):
        super().__init__(model_name, state, provenance_tracker, major_stage)

    def _run(
        self,
        store: RecordStore,
        workspace: Workspace,
    ) -> RecordStore:
        """
        Executes the ATLAS model run.

        Args:
            store (RecordStore): The input data generated by the preprocessor.
            workspace (Workspace): The workspace object for path management.

        Returns:
            RecordStore: The raw output files that have been prepared to run the model.

        Notes:
            - All preprocessing and postprocessing should be handled outside this method.
            - This method only runs the ATLAS container and records provenance for the run.
        """
        logger.info(
            "[AtlasRunner] Starting ATLAS model run for year %s",
            self.state.current_year,
        )
        settings = self.state.full_settings

        # Get container configuration
        vehicle_ownership_model, atlas_image = self.get_model_and_image(
            settings, "vehicle_ownership_model"
        )

        atlas_docker_vols = get_atlas_docker_vols(settings, workspace)
        freq = settings.run.vehicle_ownership_freq
        npe = settings.atlas.num_processes
        container_input_dir = settings.atlas.container_input_folder
        container_output_dir = settings.atlas.container_output_folder
        sample_size = settings.atlas.sample_size
        # BEAMAC is an integer flag that controls accessibility calculation
        # 0 = no accessibility calculation
        # 1 = use BEAM skims to calculate accessibility
        # 2 = use BEAM skims to calculate accessibility, but only for the first year
        beamac = settings.atlas.beamac
        mod = settings.atlas.mod
        adscen = settings.atlas.adscen
        rebfactor = settings.atlas.rebfactor
        taxfactor = settings.atlas.taxfactor
        discIncent = settings.atlas.discIncent
        atlas_cmd = get_atlas_cmd(
            settings,
            freq,
            self.state.forecast_year,
            npe,
            sample_size,
            beamac,
            mod,
            adscen,
            rebfactor,
            taxfactor,
            discIncent,
        )

        # Initialize container client
        client = None

        # Execute container
        atlas_output_dir = workspace.get_atlas_output_dir()
        output_year = self.state.forecast_year
        expected_output_filenames = [
            f"householdv_{output_year}.csv",
            f"vehicles_{output_year}.csv",
        ]
        # Create full paths for Consist tracking
        expected_output_paths = [
            os.path.join(atlas_output_dir, f) for f in expected_output_filenames
        ]

        input_paths = [r.file_path for r in store.all_records()]

        # Execute container
        try:
            logger.info(
                "[AtlasRunner] Running Atlas vehicle ownership model container for year %s",
                self.state.current_year,
            )
            max_retries = settings.atlas.max_retries
            success = False

            for i in range(max_retries):
                success = self.run_container(
                    client=client,
                    settings=settings,
                    image=atlas_image,
                    volumes=atlas_docker_vols,
                    command=atlas_cmd,
                    model_name=self.model_name,
                    working_dir="/",
                    provenance_tracker=self.provenance_tracker,
                    # PASS INPUTS HERE
                    input_artifacts=input_paths,
                    # PASS OUTPUTS HERE
                    output_paths=expected_output_paths,
                )

                if not success:
                    logger.error(f"ATLAS container execution failed in attempt {i + 1}")
                else:
                    logger.info(
                        f"ATLAS container execution succeeded in attempt {i + 1}"
                    )
                    break

            if not success:
                raise RuntimeError(
                    "ATLAS container execution failed after all retry attempts"
                )

        except Exception as e:
            logger.error(f"ATLAS container execution error: {e}")
            raise

        # 1. Define Expected Outputs EARLY (so we can pass to Consist)
        output_records = []
        for output_path in expected_output_paths:
            if os.path.exists(output_path):
                from pilates.generic.records import FileRecord

                # Extract filename for short_name
                fname = os.path.basename(output_path)

                output_record = FileRecord(
                    file_path=output_path,
                    models=[self.model_name],
                    year=output_year,
                    description=f"ATLAS {fname} output for year {output_year}",
                    short_name=fname.replace(".csv", ""),
                    uri=(
                        self.provenance_tracker.to_uri(output_path)
                        if self.provenance_tracker and hasattr(self.provenance_tracker, "to_uri")
                        else None
                    ),
                )
                output_records.append(output_record)
            else:
                logger.warning(f"Expected ATLAS output file not found: {output_path}")

        logger.info(
            "[AtlasRunner] ATLAS model run complete for year %s (outputs=%d)",
            self.state.current_year,
            len(output_records),
        )

        # CRITICAL FIX: Explicitly set status to 'completed'
        return RecordStore(recordList=output_records)
