import logging
import os
import pandas as pd

from pilates.utils.io import read_datastore
from pilates.utils.settings_helper import get as get_setting

logger = logging.getLogger(__name__)


def generate_canonical_zones_file(settings, year, output_path):
    """
    Generates the canonical_zones.csv file from the authoritative datastore.
    This file becomes the single source of truth for zone ordering and mapping.

    The output file will have two columns:
    - zone_key: The unique, stable identifier for the zone (e.g., GEOID or TAZ ID).
    - asim_id: A 1-based sequential integer used for matrix indexing.

    Args:
        settings (PilatesConfig): The simulation configuration.
        year (int): The year to read from the datastore.
        output_path (str): The path to write the canonical_zones.csv file.
    """
    logger.info(f"--- Generating Canonical Zones File at {output_path} ---")
    zone_type = get_setting(settings, "shared.skims.zone_type")
    
    df = None
    
    if os.path.exists(output_path):
        logger.info("Canonical zones file already exists. Skipping generation.")
        return output_path

    if zone_type == "block_group":
        # For block groups, the zone_key is the GEOID.
        # The asim_id is the existing TAZ ID from the land_use table.
        store, table_prefix_yr = read_datastore(settings, year)
        land_use_key = os.path.join(table_prefix_yr, "land_use")
        if land_use_key not in store:
            land_use_key = "land_use"
        
        land_use = store.get(land_use_key)
        store.close()
        
        if land_use is None:
            raise KeyError(f"Could not find '{land_use_key}' table in datastore.")
        if 'geoid10' not in land_use.columns or 'TAZ' not in land_use.columns:
            raise ValueError("land_use table for block_group must contain 'geoid10' and 'TAZ' columns.")
        
        df = land_use[['geoid10', 'TAZ']].copy()
        df.rename(columns={'geoid10': 'zone_key', 'TAZ': 'asim_id'}, inplace=True)

    elif zone_type == "taz":
        # For TAZs, the zone_key is the TAZ ID itself (e.g., from taz1454).
        # A new, sequential asim_id is generated for matrix indexing.
        store, table_prefix_yr = read_datastore(settings, year)
        blocks_key = os.path.join(table_prefix_yr, "blocks")
        if blocks_key not in store:
            blocks_key = "blocks"
            
        blocks = store.get(blocks_key)
        store.close()
        
        if blocks is None:
            raise KeyError(f"Could not find '{blocks_key}' table in datastore.")
        
        taz_col = 'taz_zone_id'  # Verified from H5 inspection
        if taz_col not in blocks.columns:
            raise ValueError(f"'{taz_col}' not found in 'blocks' table.")
            
        unique_tazs = blocks[taz_col].unique()
        unique_tazs.sort()  # Ensure stable order before assigning IDs
        df = pd.DataFrame({'zone_key': unique_tazs})
        df['asim_id'] = range(1, len(df) + 1)

    if df is not None:
        # Final processing and save
        df['zone_key'] = df['zone_key'].astype(str)
        df['asim_id'] = df['asim_id'].astype(int)
        df = df.sort_values('asim_id').reset_index(drop=True)
        
        df.to_csv(output_path, index=False)
        logger.info(f"Successfully generated canonical zones file with {len(df)} zones.")
        return output_path
    else:
        raise ValueError(f"Unsupported zone_type for canonical zone generation: {zone_type}")


def get_canonical_zones(workspace):
    """
    Reads the canonical_zones.csv file from the workspace root.
    
    Args:
        workspace (Workspace): The current run's workspace.

    Returns:
        pd.DataFrame: DataFrame with 'zone_key' and 'asim_id' columns.
    """
    path = os.path.join(workspace.full_path, 'canonical_zones.csv')
    if not os.path.exists(path):
        raise FileNotFoundError(
            "canonical_zones.csv not found. It should be generated by the initialization step."
        )
    return pd.read_csv(path, dtype={'zone_key': str, 'asim_id': int})


def get_block_to_zone_mapping(settings, year):
    """
    Returns a mapping from block GEOID to the TAZ zone ID it belongs to.
    This is used by ActivitySim to assign households/persons to zones.
    The authoritative source is the 'blocks' table in the datastore.
    """
    logger.info(f"--- Getting Block to Zone Mapping for year {year} ---")

    store, table_prefix_yr = read_datastore(settings, year)
    blocks_key = os.path.join(table_prefix_yr, "blocks")
    if blocks_key not in store:
        blocks_key = "blocks"

    blocks = store.get(blocks_key)
    store.close()

    if blocks is None:
        raise KeyError(f"Could not find '{blocks_key}' table in datastore.")

    taz_col = 'taz_zone_id'
    if taz_col not in blocks.columns:
        raise ValueError(f"'{taz_col}' not found in 'blocks' table.")

    # The index of the blocks table is the block GEOID (e.g., 'block_id')
    # We need to ensure the index is what we think it is.
    if blocks.index.name != 'block_id':
        logger.warning(f"Blocks table index is named '{blocks.index.name}', expected 'block_id'. Assuming it contains GEOIDs.")

    mapping_df = blocks[[taz_col]]
    mapping = mapping_df[taz_col].to_dict()
    logger.info(f"Successfully created block to zone mapping for {len(mapping)} blocks.")

    return mapping


