#########################################################################################################

############################
#     POLARIS SETTINGS     #
############################

data_dir : /mnt/c/polaris_development/PILATES/campoInputs
backup_dir : /mnt/c/polaris_development/PILATES/Backup/campoInputs
db_name : campo
out_name : Campo_abm
polaris_exe :  /mnt/c/polaris_development/polaris-wsl/build/release/bin/Integrated_Model
scenario_file : scenario_run10p_urbansim.json
num_threads : 12
block_loc_file_name : campo_block_to_loc.csv
auto_skim_file : highway_skim_file.bin
transit_skim_file : transit_skim_file.bin
vot_level : 2

# convergence settings
results_dir : convergence_results  # = data_dir / json_data["results_dir"]
scripts_dir :  /mnt/c/polaris_development/PILATES/pilates/polaris/conv_scripts # = Path(json_data["scripts_dir"])

# -- SET THE MAIN AND DTA RUN SCENARIO FILES
population_scale_factor : 0.10  # MUST match settings in the scenario files below
scenario_main_init : scenario_run10p_urbansim_init.json #= json_data["scenario_main_init"]
scenario_main :  scenario_run10p_urbansim.json # = json_data["scenario_main"]

# -- ENTER THE NUMBER OF MAIN RUNS AND DTA RUNS PER MAIN RUN
num_abm_runs : 4  # = json_data["num_abm_runs"]
